### ISSUE TITLE
JavaFX build fails with gcc 6 [JDK-8189689]

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#12]
See https://bugs.openjdk.java.net/browse/JDK-8088144
There is a PR to fix this in https://github.com/javafxports/openjdk-jfx/pull/11

**Comment by bourgesl** [comment]
See also the bug I reported:
https://bugs.openjdk.java.net/browse/JDK-8189689

**Comment by bourgesl** [comment]
The PR seems good so I should accept the PR on the dev branch and then start a webrev for Emmanuel or should I ask him to start the review ?

**Comment by bourgesl** [comment]
Here is the webrev merging  PR #11 et #16 from contributor @ebourg:
http://cr.openjdk.java.net/~lbourges/fx/fx-8189689.0/

**Comment by bourgesl** [comment]
Follow RFR at https://bugs.openjdk.java.net/browse/JDK-8189689

**Comment by bourgesl** [comment]
Changeset pushed:
http://hg.openjdk.java.net/openjfx/jfx-dev/rt/rev/6d279ecfacd1
