### ISSUE TITLE
JDK-8207328: Javadocs of Stylesheet are outdated

### ISSUE THREAD

**Issue by wowselim** [javafxports/openjdk-jfx#122]
`javafx.css.Stylesheet` javadocs are a bit confusing. For example the `convertToBinary` method receives two `java.io.File` parameters, while talking about URLs. Similarly the `loadBinary` method receives a URL but talks about the parameter as `InputStream`.
On a side note, the `getUrl` method returns a String which is also a bit confusing.

https://docs.oracle.com/javase/9/docs/api/javafx/css/Stylesheet.html

**Comment by nlisker** [comment]
Added to [JDK-8204653](https://bugs.openjdk.java.net/browse/JDK-8204653).

**Comment by wowselim** [comment]
Hi @nlisker ,

I have sent my signed contributor agreement to oracle and I'm waiting for a reply. Can I fix the mentioned javadocs myself and submit a pull request? I can see that the issue you linked is assigned to you so I wanted to ask before I do anything.

Selim

**Comment by nlisker** [comment]
Yes, I'll unlink it.

**Comment by kevinrushforth** [comment]
@wowselim we will need to wait for your OCA to be recorded before we can act on your PR.

**Comment by nlisker** [comment]
@wowselim Note that late July is the deadline (unless stated otherwise) to push this change into 11, so if you don't get it done by that point, I'll want to do it myself. Did you submit a JBS issue?

**Comment by wowselim** [comment]
hi @nlisker I don't have an account on the bug tracker. I also didn't receive a reply from oracle regarding my agreement yet. The changes are on my fork already but I can't really do anything...

**Comment by nlisker** [comment]
@wowselim You don't need an account, submit the bug through https://bugreport.java.com/bugreport/. @kevinrushforth can move it. Maybe he can check on your OCA while at it.

**Comment by wowselim** [comment]
I wasn't aware of that, I created an issue now (internal ID : 9056056)

**Comment by kevinrushforth** [comment]
It has been transferred to the JDK project as [JDK-8207328](https://bugs.openjdk.java.net/browse/JDK-8207328)

**Comment by kevinrushforth** [comment]
Regarding the OCA, I can check on it.

**Comment by wowselim** [comment]
@kevinrushforth sorry to bug you but are there any news regarding my OCA? Otherwise I suggest @nlisker just takes this issue since the deadline seems to be too close now.

**Comment by kevinrushforth** [comment]
@wowselim I sent an inquiry today and will update you as soon as I hear back

**Comment by wowselim** [comment]
I forgot to link to this issue from my commit message but I created following pull request: https://github.com/javafxports/openjdk-jfx/pull/147
