### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#130]
Since PR#83 is merged into develop, AppVeyor builds fail (travis still succeeds). That PR always had a succeeding AppVeyor build before, so I wonder what is wrong.
Looking into the appveyor logs at https://ci.appveyor.com/project/javafxports-github-bot/openjdk-jfx/build/develop%20636 it seems the build is successful, but then something goes wrong with caches:

Cache 'C:\Users\appveyor\.gradle\wrapper' - Calculating dependencies checksum...Error calculating dependencies CRC for C:\Users\appveyo      r\.gradle\wrapper: Error calculating CRC32 for C:\projects\openjdk-jfx\.gradle-wrapper\gradle-wrapper.properties: The system cannot find the path       specified

**Comment by johanvos** [comment]
Probably related to #95

**Comment by brcolow** [comment]
The linked issue is the reason why. The path is wrong in `appveyor.yml`.

` - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties`

Should be:

` - C:\Users\appveyor\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties`
