### ISSUE TITLE
JDK-8208173: isComplexCharCode() returns false for U+11FF

### ISSUE THREAD

**Issue by nakajima-akira** [javafxports/openjdk-jfx#133]
modules/javafx.graphics/src/main/java/com/sun/javafx/text/ScriptMapper.java

        else if (code < 0x11ff) { // U+1100 - U+11FF Old Hangul
            return true;
        }

---->  Fix

        else if (code <= 0x11ff) { // U+1100 - U+11FF Old Hangul
            return true;
        }

**Comment by nakajima-akira** [comment]
Do I need to report this bug to [http://bugreport.java.com/](http://bugreport.java.com/)?
This bug code is that **_=_** is missing only.

**Comment by kevinrushforth** [comment]
> Do I need to report this bug to http://bugreport.java.com/?

Yes.

**Comment by nakajima-akira** [comment]
BUG-ID was published.
[https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8208173](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8208173)

**Comment by kevinrushforth** [comment]
Do you plan to submit a PR for this bug? We are almost out of time for these sort of bugs for openjfx11.

**Comment by nakajima-akira** [comment]
If no one does, I will do it.
openjfx11 is too late to patch from now.
My all patches (including already posted. PR 125,126,137) is for openjfx12.
