### ISSUE TITLE
build fails for platforms that don't include Swing

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#148]
When Swing is not included in a project (e.g. for embedded), building fails as there is no task for publishing the Swing artifacts.

**Comment by johanvos** [comment]
This can be fixed by https://github.com/johanvos/openjdk-jfx/commit/e9ab2a9ce895a5cb0b18c9e696978e6342dce017 which should be part of an upcoming PR

**Comment by kevinrushforth** [comment]
Did you want to get this into openjfx/11?
