### ISSUE TITLE
monocle setBounds width/height mixup

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#171]
MonocleWindow has a bug in _setBounds where the contentWidth is checked instead of contentHeight. It's unlikely this happens, but nevertheless would be good to correct.

**Comment by kevinrushforth** [comment]
Tracked in JBS as [JDK-8209969](https://bugs.openjdk.java.net/browse/JDK-8209969)

**Comment by johanvos** [comment]
Fixed by https://github.com/javafxports/openjdk-jfx/commit/3fbd1165a31cf07a4dcb6c854597adeccc4af7c7
