### ISSUE TITLE
javafx 11 runtime exception

### ISSUE THREAD

**Issue by halimpuckjava** [javafxports/openjdk-jfx#179]
hi

i use jdk 11-ea 28 javafx 11-ea+24 in windows 10 x64 (with maven project), in execution i see this exception : Error: JavaFX runtime components are missing, and are required to run this application

what's wrong and how to fix that ??

**Comment by kevinrushforth** [comment]
JavaFX is no longer bundled with the JDK, but is distributed as a separate library. Please see the [OpenJFX Download](https://wiki.openjdk.java.net/display/OpenJFX/Download) page.

**Comment by kevinrushforth** [comment]
I should add that you can also go directly to the [Gluon JavaFX](https://gluonhq.com/products/javafx/) page, which will point you to the [instructions](http://docs.gluonhq.com/javafx11/) for using the JavaFX maven modules.

**Comment by klausenbusk** [comment]
> I should add that you can also go directly to the [Gluon JavaFX](https://gluonhq.com/products/javafx/) page, which will point you to the [instructions](http://docs.gluonhq.com/javafx11/) for using the JavaFX maven modules.

I'm getting the same error when using the maven module, but I suspect it is due to Eclipse. It should work with OpenJDK 10 right? or do I need to use OpenJDK 11?

**Comment by klausenbusk** [comment]
> I'm getting the same error when using the maven module, but I suspect it is due to Eclipse. It should work with OpenJDK 10 right? or do I need to use OpenJDK 11?

I managed to solve it by adding a `module-info.java` file (I'm new to java), sorry for the noise :)

**Comment by nlisker** [comment]
@klausenbusk You've ran into https://bugs.eclipse.org/bugs/show_bug.cgi?id=534572. If your project is not a modular you will get this error, but as you've discovered, modularizing your project is a workaround.

**Comment by klausenbusk** [comment]
> @klausenbusk You've ran into https://bugs.eclipse.org/bugs/show_bug.cgi?id=534572. If your project is not a modular you will get this error, but as you've discovered, modularizing your project is a workaround.

I'm already running Eclipse 4.9 so I think it is a difference issue? As mentioned here: https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426576176 I think the current JVM code require modularizing.

**Comment by Aaris-Kazi** [comment]
I'm implementing JavaFX for the first time for the better UI, but the time I compiled this message came
I'm using Visual Studio I had imported the jar files but the time of execution I get this error

Error: JavaFX runtime components are missing, and are required to run this application

**Comment by ghost** [comment]
> 
> 
> I'm implementing JavaFX for the first time for the better UI, but the time I compiled this message came
> I'm using Visual Studio I had imported the jar files but the time of execution I get this error
> 
> Error: JavaFX runtime components are missing, and are required to run this application

@Aaris-Kazi, I was also facing the same issue and it can be resolved by adding vmArgs in the launch.json file 

`"vmArgs": "--module-path \"C:\\Program Files\\Java\\javafx-sdk-11.0.2\\lib\" --add-modules javafx.controls,javafx.fxml"`

![Screenshot (66)](https://user-images.githubusercontent.com/53997634/98505818-09c51000-2280-11eb-8581-44ee7d9acebb.png)
