### ISSUE TITLE
WebView JavaFX 8 and JavaFX11

### ISSUE THREAD

**Issue by scientificware** [javafxports/openjdk-jfx#186]
Linux : WebView different behaviours with JavaFX 8 and JavaFX 11.

```
public class NavigateurTest extends Application {

    final StackPane root = new StackPane();
    final WebView webView =  new WebView();
    
    public void init() {    
        root.getChildren().add(webView);
    }

    @Override
    public void start(Stage primaryStage) {    
        webView.getEngine().load("https://duckduckgo.com");
        primaryStage.setTitle("OpenJFX MathML Rendering WebBrowser Test ");
        primaryStage.setScene(new Scene(root));
        primaryStage.show();

    }
}
```

JavaFX8 171 and 192
- http://google.com
  - Some search TextField border are missing,
  - ScrollBar missing,
![screenshot_20180831_023241](https://user-images.githubusercontent.com/19194678/44886590-779c4700-acc7-11e8-9eb8-b89e02f28342.png)
  - When one reduces the window and ScrollBar becomes visible its cursor and spin buttons are missing.
![screenshot_20180831_024740](https://user-images.githubusercontent.com/19194678/44886732-8c2d0f00-acc8-11e8-9880-62dd1cc40573.png)
- http://duckduckgo.com
  - The logo of the website is not displayed.
![screenshot_20180831_030020](https://user-images.githubusercontent.com/19194678/44887012-4e30ea80-acca-11e8-8be8-5c8db33a9cc8.png)
- This also affects MathML display. Fraction and root lines are not displayed.
![screenshot_20180831_030638](https://user-images.githubusercontent.com/19194678/44887180-29894280-accb-11e8-9b9d-f5a9419b47f5.png)

JavaFX11
![screenshot_20180831_023320](https://user-images.githubusercontent.com/19194678/44886599-8256dc00-acc7-11e8-9674-4e4e3fc2b090.png)
![screenshot_20180831_030113](https://user-images.githubusercontent.com/19194678/44887026-66086e80-acca-11e8-8c21-41d833768b69.png)
![screenshot_20180831_030914](https://user-images.githubusercontent.com/19194678/44887243-8684f880-accb-11e8-8fe9-acebb557c43e.png)

**Comment by kevinrushforth** [comment]
The WebKit library is (nearly) identical between 8u192 ea and openjfx 11. There might be any number of differences in other code (for example, graphics code) that could explain the different behavior. In general, other than WebKit, only a small number of critical fixes are backported to 8u-dev.

**Comment by scientificware** [comment]
@kevinrushforth I made the previous tests with Linux. Today, I try Windows. I can't test with macOS.

Windows is not affected :
- Windows 10 JavaFX 8 171 and 192
![screenshot_20180831_104800](https://user-images.githubusercontent.com/19194678/44902991-b2c06980-ad0b-11e8-90c6-48891e4efc81.png)
![screenshot_20180831_102000](https://user-images.githubusercontent.com/19194678/44902813-3cbc0280-ad0b-11e8-95ed-26e172e18390.png)
![screenshot_20180831_102600](https://user-images.githubusercontent.com/19194678/44902496-750f1100-ad0a-11e8-924d-eec9b144f19f.png)

**Comment by scientificware** [comment]
MathML side, the problem affect elements who use `PaintInfo.context` :

- The code drawing fraction line : [RenderMathMLFraction::paint](https://github.com/javafxports/openjdk-jfx/blob/e9156aba8b28462a4a1a8626a12eb0e02f63ef8d/modules/javafx.web/src/main/native/Source/WebCore/rendering/mathml/RenderMathMLFraction.cpp#L254)

- The code drawing root line : [RenderMathMLRoot::paint](https://github.com/javafxports/openjdk-jfx/blob/e9156aba8b28462a4a1a8626a12eb0e02f63ef8d/modules/javafx.web/src/main/native/Source/WebCore/rendering/mathml/RenderMathMLRoot.cpp#L267)

**Comment by kevinrushforth** [comment]
This makes it even more likely a graphics problem rather than a WebView problem.

I will also note that this GitHub issue tracker is not the right place to track bugs against JDK 8u, so unless there is a bug in openjfx 11 (or 12), this issue should be closed.
