### ISSUE TITLE
Sync from HG repo to master branch seems to be stuck

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#190]
The hourly sync from the upstream HG jfx-dev/rt repo on openjdk to the master branch of this git repo seems to be stuck. [This changeset](http://hg.openjdk.java.net/openjfx/jfx-dev/rt/rev/30c0d3317713) was pushed to HG two hours ago and still has not shown up in the git repo.

**Comment by johanvos** [comment]
The server with the jenkins jobs to synchronize seems to be down. We'll look into it.

**Comment by johanvos** [comment]
Jenkins is back up and running, and syncing seems to work again. The changeset you referred to is now in github: https://github.com/javafxports/openjdk-jfx/commit/4783d5e922d1f75af2c175c243c7f7511458aaf2

**Comment by kevinrushforth** [comment]
Thanks, looks fine now.

**Comment by kevinrushforth** [comment]
Btw, the commit that corresponds to the HG changeset is: [3359161](https://github.com/javafxports/openjdk-jfx/commit/3359161778bca77091190a8aec7db9b7a92ceb10) (and yes, it is there).
