### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by plata** [javafxports/openjdk-jfx#209]
Do you consider providing a flatpak extension such that it's possible to build JavaFX flatpaks without shipping the JRE? This is especially interesting now that JDK and JFX get separated and JFX becomes standalone with v11.

**Comment by kevinrushforth** [comment]
This is not likely something we would do as part of JavaFX.

We already build and distribute maven modules, which can be used by your application along with any other maven modules. We also ship jmods, which can be used to create a JDK image with your application and the needed JavaFX modules.
