### ISSUE TITLE
The DialogPane instance created as a default value of ObjectProperty dialogPane will be rewritten in the default constructor (L268)

### ISSUE THREAD

**Issue by MaridProject** [javafxports/openjdk-jfx#210]
https://github.com/javafxports/openjdk-jfx/blob/25fcdad5e78df52b3f195a0a73053c6c0efaa869/modules/javafx.controls/src/main/java/javafx/scene/control/Dialog.java#L511

**Comment by eugener** [comment]
Please https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md which will explains how to properly submit an issue.

**Comment by MaridProject** [comment]
Thanks
