### ISSUE TITLE
java 8 support?

### ISSUE THREAD

**Issue by os72** [javafxports/openjdk-jfx#212]
Would it be possible to provide builds compatible with Java 8?

`java.lang.UnsupportedClassVersionError: javafx/util/Pair has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by kevinrushforth** [comment]
No, this is not possible. JavaFX 11 requires JDK 10 or later.

JDK 8 from Oracle already includes JavaFX. If you want to build JavaFX 8 for a different JDK 8, then then sources are here: http://hg.openjdk.java.net/openjfx/8u-dev/rt
