### ISSUE TITLE
scheduleDispatchFunctionsOnMainThread uses different ClassLoader

### ISSUE THREAD

**Issue by clouds56** [javafxports/openjdk-jfx#220]
I'm working on an intellij plugin that using javafx and found that when use data url as image source, the image could not be successfully rendered. (Note that the intellij platform would use its own com.intellij.util.lang.UrlClassLoader other than sun.misc.Launcher$AppClassLoader to load everything, whose parent is null, [see here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206767585-Different-ClassLoaders) for more information)
After investigating, I found that `scheduleDispatchFunctionsOnMainThread` https://github.com/javafxports/openjdk-jfx/blob/a42b5841674ab7cd2704e0ea5fbcc94934d91c83/modules/javafx.web/src/main/native/Source/WTF/wtf/java/MainThreadJava.cpp#L11-L26 called by `callOnMainThread` in https://github.com/javafxports/openjdk-jfx/blob/4f0addff16de7182752bc60541f44baeb0e99d2a/modules/javafx.web/src/main/native/Source/WebCore/platform/network/DataURLDecoder.cpp#L181-L203 would uses system's default ClassLoader (as in a new thread) for class `com.sun.webkit.MainThread` and `com.sun.webkit.Invoker` other than the caller's ClassLoader.

Is it possible to provide some workaround here? like caching the "com/sun/webkit/MainThread" class so that we could use the correct method.

**Comment by pgschulz** [comment]
The behaviour makes it unusable for osgi-environments as well, because the default classloader in such environments does not find the "com/sun/webkit/MainThread" - MainThread class can only be found  by the bundle classloader.

**Comment by kevinrushforth** [comment]
@pgschulz or @clouds56 - if you can provide a test program that shows this problem, then we can take a look.

**Comment by pgschulz** [comment]
[breaksfxwebkit.zip](https://github.com/javafxports/openjdk-jfx/files/3125252/breaksfxwebkit.zip)
@kevinrushforth hope this will show my problem. Maybe it is good to read https://www.eclipse.org/forums/index.php/t/1096912/ before.

**Comment by ararunprasad** [comment]
@pgschulz , Thanks for providing the test.
Sorry, I'm not used to OSGi. Could you elaborate the steps to run test app?

**Comment by pgschulz** [comment]
You are welcome, thanks for looking at it!

Well, the easiest way is to use Eclipse:
- Unzip the project
- Import as "existing project"
- Open test.target and "Set as Active Target Platform", this will trigger download and build
- Right click on osgiopenjfx.launch and choose "run as" -> "osgiopenjfx"

@ararunprasad If this does not help you, let me know.

**Comment by kevinrushforth** [comment]
@pgschulz this isn't quite what we are looking for in terms of a standalone test.

When you say 'import as "existing project"' I presume you mean with Eclipse? We really need something that doesn't require an IDE and doesn't need to download code. Ideally something that has source code, a build script, and set of instructions for building and running it.

**Comment by ararunprasad** [comment]
I agree with @kevinrushforth. I tried to follow the steps described by @pgschulz , but I failed miserably.

**Comment by pgschulz** [comment]
@ararunprasad Oh, I'm sorry, I'm used to work in Eclipse. I have to think about how I can provide you with something else (easy to run).

**Comment by pgschulz** [comment]
@ararunprasad What kind of operating system do you use?

**Comment by ararunprasad** [comment]
I have access to all major 3(windows, linux and mac). I primarily use mac.

**Comment by pgschulz** [comment]
Sorry, was busy. Hope this one will help you. 
[openjfx.zip](https://github.com/javafxports/openjdk-jfx/files/3717932/openjfx.zip)

**Comment by ararunprasad** [comment]
I see the following error,

[INFO] Scanning for projects...
/Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/.polyglot.build.properties
/Users/ARAJKUMA/Downloads/test/rcp.demo.feature/.polyglot.build.properties
[INFO] Computing target platform for MavenProject: com.stegmannsystems.rcp:rcp.demo.plugin.application:1.0.0-SNAPSHOT @ /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/.polyglot.build.properties
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2018-12/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2018-12/
[INFO] Adding repository http://download.eclipse.org/releases/2018-12
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2018-12/
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2018-12/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2018-12/201812191000/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2018-12/201812191000/
[INFO] Adding repository https://downloads.efxclipse.bestsolution.at/p2-repos/openjfx-11/repository
[INFO] Adding repository http://download.eclipse.org/efxclipse/runtime-nightly/site
[INFO] Resolving dependencies of MavenProject: com.stegmannsystems.rcp:rcp.demo.plugin.application:1.0.0-SNAPSHOT @ /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/.polyglot.build.properties
[ERROR] Cannot resolve target definition:
[ERROR]   Problems resolving provisioning plan.:
[ERROR]      Unable to satisfy dependency from tycho-ee-1558014829436 0.0.0.1558014829436 to org.eclipse.equinox.p2.iu; a.jre.javase [12.0.0,12.0.0].
[ERROR]
[ERROR] Failed to resolve target definition /Users/ARAJKUMA/Downloads/test/rcp.demo.target/rcp.demo.target.target: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by pgschulz** [comment]
Can you it with java 11 on your path?

**Comment by ararunprasad** [comment]
I see the following error with JDK-11,

[INFO] Compiling 3 source files to /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for rcp.demo.root 1.0.0-SNAPSHOT:
[INFO]
[INFO] rcp.demo.root ...................................... SUCCESS [  9.780 s]
[INFO] rcp.demo.plugin.application ........................ FAILURE [03:12 min]
[INFO] rcp.demo.feature ................................... SKIPPED
[INFO] rcp.demo.update .................................... SKIPPED
[INFO] rcp.demo.product ................................... SKIPPED
[INFO] rcp.demo.target .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:58 min
[INFO] Finished at: 2019-05-16T19:40:51+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.4.0:compile (default-compile) on project rcp.demo.plugin.application: Compilation failure: Compilation failure:
[ERROR] /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/src/rcp/demo/plugin/application/FirstPart.java:[9]
[ERROR] 	import javafx.embed.swt.FXCanvas;
[ERROR] 	       ^^^^^^^^^^^^
[ERROR] The import javafx.embed cannot be resolved
[ERROR] /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/src/rcp/demo/plugin/application/FirstPart.java:[25]
[ERROR] 	final FXCanvas fxCanvas = new FXCanvas(parent, SWT.NONE)
[ERROR] 	      ^^^^^^^^
[ERROR] FXCanvas cannot be resolved to a type
[ERROR] /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/src/rcp/demo/plugin/application/FirstPart.java:[25]
[ERROR] 	final FXCanvas fxCanvas = new FXCanvas(parent, SWT.NONE)
[ERROR] 	                              ^^^^^^^^
[ERROR] FXCanvas cannot be resolved to a type
[ERROR] /Users/ARAJKUMA/Downloads/test/rcp.demo.plugin.application/src/rcp/demo/plugin/application/FirstPart.java:[28]
[ERROR] 	public Point computeSize(final int wHint, final int hHint, final boolean changed)
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method computeSize(int, int, boolean) of type new FXCanvas(){} must override or implement a supertype method
[ERROR] 4 problems (4 errors)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rcp.demo.plugin.application

**Comment by pgschulz** [comment]
Did you set environment variable JAVAFX_HOME like mentioned in README.md?

**Comment by ararunprasad** [comment]
export JAVAFX_HOME=$HOME/openjfx-dev/jfx-dev/rt/build/sdk/lib

It fails with JAVAFX_HOME also. Am I doing something wrong?

**Comment by pgschulz** [comment]
Do you use Windows? Can you use export in Windows? Open cmd and run "echo %JAVAFX_HOME%" to check? Or replace ${env.JAVAFX_HOME} in rcp.demo.parent/pom.xml with path to your lib folder...

**Comment by ararunprasad** [comment]
I don't see the usage of JAVAFX_HOME env variable in any file except README.md.
```
$ grep -rn JAVAFX_HOME .
./README.md:2:Let JAVAFX_HOME environment variable point to your javafx-lib directory.
```

I use macOS, will try on Windows tomorrow.

**Comment by pgschulz** [comment]
Sorry, I uploaded it twice, you were to fast and got the version without the environment variable. Hope it works on Windows.

**Comment by pgschulz** [comment]
@arajkumar Did you try it?

**Comment by arajkumar** [comment]
@pgschulz , I didn't get a chance to access my Windows machine.

**Comment by pgschulz** [comment]
@arajkumar Is there any news?

**Comment by arajkumar** [comment]
Not actively working on this due to Windows dependency. If at all possible, could you provide a test which runs on macOS?

**Comment by pgschulz** [comment]
I don't have a mac available. I could try to use some kind of virtual environment, but I don't know when I have time and if I succeed.

**Comment by alexsuter** [comment]
Is there any workaround for that problem?

**Comment by pgschulz** [comment]
@arajkumar Any chance you will access your Windows machine? Are you sure you will look at it if I provide a Mac build? I can't waste time in setting um a Mac VM, make the test to run on mac if there is no possible benefit in it.

**Comment by pgschulz** [comment]
@kevinrushforth Is there any news on this one? Any chance the behavior will be changed in a future version?

**Comment by pgschulz** [comment]
@kevinrushforth Is there any news on this one? Any chance the behavior will be changed in a future version?

**Comment by kevinrushforth** [comment]
@pgschulz - We haven't had a chance to look into this. So that it doesn't get lost, can you file a bug at [bugreport.java.com](https://bugreport.java.com)? That way it will get into JBS, which is the official issue tracker for JavaFX. This issue tracker has been used only as a convenience and isn't actively tracked or managed. With the upcoming move of the official OpenJFX repo from Mercurial to https://github.com/openjdk/jfx we will stop using it altogether.

**Comment by pgschulz** [comment]
@kevinrushforth Thanks, I will.

**Comment by kevinrushforth** [comment]
https://bugs.openjdk.java.net/browse/JDK-8231869

**Comment by guruhb** [comment]
In order to use OpenJFX class in OSGi ecosystem, Please use "org.eclipse.osgi.internal.hookregistry.ClassLoaderHook" . 
ref 1 : 
efxclipse-rt uses this strategy to load OpenJFX classes in run time : https://github.com/eclipse-efx/efxclipse-rt/issues/217 

ref 2 : 
jmc uses OpenJFX with ClassLoaderHook (http://hg.openjdk.java.net/jmc/jmc/rev/2cc768144a86) 
stub module which is responsible for loading Module classes and exports the class to other OSGi Bundle (plugin).
Integrating OpenJFX artifacts from Maven :  http://hg.openjdk.java.net/jmc/jmc/rev/8c017a4ff44a

**Comment by pgschulz** [comment]
@guruhb Thanks for your hint, but this is exactly what we use. It is not a general problem to use openjfx in osgi but to load a base 64 encoded picture in the WebView. I am not a classloader expert but as far as I understand it, it is not right to use the application classloader to load com.sun.webkit.MainThread and not the parent classloader.

**Comment by kevinrushforth** [comment]
@pgschulz In that case we can reopen the JBS bug.

**Comment by pgschulz** [comment]
@kevinrushforth Is there a way to modify my ticket in the openjdk bug tracker? I linked the wrong branch. The right one is:
https://github.com/StegmannSystems/rcp.demo/tree/windows-only
Thanks

**Comment by kevinrushforth** [comment]
> Is there a way to modify my ticket in the openjdk bug tracker? I linked the wrong branch. The right one is:
> https://github.com/StegmannSystems/rcp.demo/tree/windows-only

I added a comment with the correct link.
