### ISSUE TITLE
CSS: Add support for HSL color model

### ISSUE THREAD

**Issue by DJViking** [javafxports/openjdk-jfx#231]
According to the JavaFX CSS Specification:

> JavaFX CSS uses the HSB color model instead of the HSL color model.

I am working with a web developer in styling our JavaFX application in a similar style as our web application. He has been using the HSL color model with his CSS styles. He was unaware of HSB. As CSS supports both HSB and HSL, perhaps JavaFX would benefit also to support both.

**Comment by DJViking** [comment]
Should I file this on https://bugreport.java.com ?

**Comment by kevinrushforth** [comment]
https://bugs.openjdk.java.net/browse/JDK-8231645
