### ISSUE TITLE
CSS: Add  support for custom properties lookup beyond Color

### ISSUE THREAD

**Issue by DJViking** [javafxports/openjdk-jfx#232]
According to the JavaFX CSS Specification, Colors are the only properties that support lookup to custom properties.

```
.root {
  --primary--background-color: black;
  --secondary-background-color: rgb(0, 0, 0);
}
```

It would benefit a lot having support to define custom properties for more than just colors, Size, Font.

```
.root {
  --primary-font-family: "Segoe UI Semibold";
  --secondary-font-family: "Roboto";
  --primary-padding: 10px;
  --secondary-padding: 5px;
}
```
It would preclude any use of a preprocessor like SASS to do this.

**Comment by DJViking** [comment]
Should I file this on https://bugreport.java.com ?

**Comment by kevinrushforth** [comment]
https://bugs.openjdk.java.net/browse/JDK-8231646
