### ISSUE TITLE
Document how to use jlink to create a Java image with javafx modules

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#238]
Issue #237 ended up being a problem with the way the custom Java image was created. We need to document how to use jlink to take a JDK plus the JavaFX jmods (optionally, plus a modular JavaFX application) and create a custom Java image that can run an application.

**Comment by kevinrushforth** [comment]
As @johanvos wrote in #237 --

> You can download the JavaFX modules as jmods, including classes and native libs. See https://gluonhq.com/products/javafx/ and download the mods (instead of the SDK).
> Next, point jlink to the mods directory (assuming you unpacked them in `/opt`)
> 
> `jlink --module-path /opt/java/jmods:/opt/javafx-jmods-11:build/hellomodule --add-modules hellomodule --launcher start=hellomodule/com.ameus.Main --output dist`
> 
> On Linux, I got it working like this, and I expect it to work similar on the other platforms.
> 
> We should document this.

**Comment by DJViking** [comment]
Very useful to know, though I reckon most would be using a build tool plugin.
Until there is a gradle-jlink-plugin or gradle-jpackager-plugin, we have to use the tools them self, and it helps knowing the various options for both Modular and Non-Modular applications.

How did you produce the build/hellomodule? I reckon you used Gradle. I have used the distributions as input to both jlink and jpackager.

**Modular project:**

    jlink \
    --module-path /usr/java/javafx-jmods-11/:build/distributions/movies-1.0.0-SNAPSHOT/lib/ \
    --add-modules no.smeaworks.movies \
    --launcher movies=no.smeaworks.movies/no.smeaworks.movies.MoviesApplication \
    --output outputDir

**Non-Modular project:**

    jlink \
    --module-path /usr/java/javafx-jmods-11/ 
    --add-modules=javafx.base \
    --add-modules=javafx.controls \
    --add-modules=javafx.fxml \
    --add-modules=javafx.graphics \
    --add-modules=javafx.web \
    --add-modules=javafx.media \
    --add-modules=javafx.swing \
    --bind-services \
    --output outputDir

**Comment by johanvos** [comment]
Doc issue created: https://github.com/openjfx/openjfx-docs/issues/9

**Comment by Rizwan-Hasan** [comment]
Thanks, it works on windows also.

**Comment by nlisker** [comment]
Can this be closed?

**Comment by kevinrushforth** [comment]
Yes, it should be closed as this is documented on https://openjfx.io/
