### ISSUE TITLE
Embedded: Error undefined pixcoord starting javafx app

### ISSUE THREAD

**Issue by dellgreen** [javafxports/openjdk-jfx#273]
[pixcoord_error.txt](https://github.com/javafxports/openjdk-jfx/files/2557179/pixcoord_error.txt)

Currently using Vivante GC2000 OpenGL ES 3.0 V6.2.4.p1.150331
If i run exact same tests on an older version of our product it works fine, it uses
Currently using Vivante GC2000 OpenGL ES 3.0 V5.0.11.p4.25762

**Comment by dellgreen** [comment]
[vivante.txt](https://github.com/javafxports/openjdk-jfx/files/2557189/vivante.txt)

**Comment by dellgreen** [comment]
I can see this was discussed back in 2016, but unclear whether a fix actually happened or whether its a regression in javafx?

http://mail.openjdk.java.net/pipermail/openjfx-dev/2016-February/018753.html

**Comment by dellgreen** [comment]
In the meantime, i'll try to downgrade vivante driver to find out when the breakage was introduced

**Comment by dellgreen** [comment]
so i have failed miserably in trying to downgrade from v6 to v5 in yocto. Any ideas on what to fix in javafx to make it usable with v6?

**Comment by johanvos** [comment]
The fix you refer to in your early comments never made it to the OpenJFX repository (we only ported it to mobile). It's probably a good time to do it now.

**Comment by dellgreen** [comment]
That would be awseome, and save my bacon, as i have rebased on latest yocto distro and cannot get our existing javafx frontend running on the device.  :)

**Comment by dellgreen** [comment]
Please let me know if you need help testing changes on our board, or any other help I can provide to to make this happen :)

**Comment by dellgreen** [comment]
Do you think its worth me trying the patches here
https://bitbucket.org/javafxports/8u60-rt/commits/595633bbaae36f98d85d47d276294442ea43488c
to see if it fixes my issue?

**Comment by dlemmermann** [comment]
Yes, this looks great. Thanks!

And I can freely share this now? Asking because we are recording the keynote session.

Dirk

**Comment by kevinrushforth** [comment]
Link to JBS bug: [JDK-8167068](https://bugs.openjdk.java.net/browse/JDK-8167068)

**Comment by kevinrushforth** [comment]
This is fixed, so closing this bug.
