### ISSUE TITLE
Unrecognized image loader with large image

### ISSUE THREAD

**Issue by phamvanthanh** [javafxports/openjdk-jfx#275]
Hi,
snapshot fails with large image
![image](https://user-images.githubusercontent.com/24784468/48257582-7a44b680-e445-11e8-8a2a-c59ba3d2a644.png)

**Comment by kevinrushforth** [comment]
This is a known issue, tracked by [JDK-8088198](https://bugs.openjdk.java.net/browse/JDK-8088198).
