### ISSUE TITLE
Consider providing explicit download links for jmods bundles for each minor versions 

### ISSUE THREAD

**Issue by fthevenet** [javafxports/openjdk-jfx#279]
When building a modular image including openjfx to distribute your app, the first step is to retrieve the mods files from https://gluonhq.com/products/javafx/.

The page provides for each platform a link that redirects to an archive file that contains the latest minor version; while this is a great way to ensure visitors get the latest version, this has the potential to break unsuspecting automated build system whenever the minor release is changed.

For example, following the recent release of version 11.0.1, while the download link remained https://gluonhq.com/download/javafx-11-jmods-xxx/, when unzipped it produced a directory named "javafx-jmods-11.0.1", when the rest of the build process expected it to be named "javafx-jmods-11".

Providing direct, normalized links for each minor releases would avoid that situation.

**Comment by tiainen** [comment]
The links were updated so that there are different links for each version. For instance, for the Windows SDK we now have the following download links:

 - JavaFX 11: https://gluonhq.com/download/javafx-11-sdk-windows/
 - JavaFX 11.0.1: https://gluonhq.com/download/javafx-11-0-1-sdk-windows/
