### ISSUE TITLE
JDK-8213541: WebView does not handle HTTP response without ContentType

### ISSUE THREAD

**Issue by Maxoudela** [javafxports/openjdk-jfx#280]
JDK issue here : https://bugs.openjdk.java.net/browse/JDK-8213541

If you try to load an URL into the WebView where the response does not specify the content-type, the Loader state switch to "cancelled".

**Comment by Maxoudela** [comment]
Ho allright, I thought it was the normal process to create a second Github issue. I'm closing it then

**Comment by kevinrushforth** [comment]
Thanks. No need for a Github issue to be created (I never do unless it is to modify Github-only files).
