### ISSUE TITLE
Consistent naming please ...

### ISSUE THREAD

**Issue by tuxedo0801** [javafxports/openjdk-jfx#286]
I know JavaFX. While searching for the future of JavaFX I stumbled on http://www.openjfx.io ... Great looking site which on the first view gives an of "JavaFX is not dead, it's alive". But what I'm now confusef about is all the different naming. The site is mixing "JavaFX" and "OpenJFX" like hell ...
And also this github repo.. it's named "openjdk-jfx", which sounds like "OpenJFX".

I have no idea who takes care of the website, but, please, can those people fix this?
Either stick to JavaFX or switch completely to OpenJFX (which I would prefer) and make a foot-note that explains that JavaFX's successor is now the community driven so called OpenJFX.

Just my 5 cents.

**Comment by kevinrushforth** [comment]
OpenJFX is the JDK project where JavaFX is developed. The packages and modules are all prefixed with javafx. The official home for the Mercurial repositories for JavaFX is https://hg.openjdk.java.net/openjfx/ and the main repo, of which this GitHub repo is a mirror is https://hg.openjdk.java.net/openjfx/jfx-dev/rt

So you are going to see the terms used somewhat interchangeably. No, we are not likely to change that.

**Comment by tuxedo0801** [comment]
The please try to clarify the naming on the website. Someone who knows in principle what JavaFX is might be confused about an "OpenJFX"-webpage that uses both names, JavaFX and OpenJFX for the same.
