### ISSUE TITLE
How to add an external dependency to openjfx

### ISSUE THREAD

**Issue by elect86** [javafxports/openjdk-jfx#292]
I'm playing around trying to add lwjgl as a dependency to the `graphics` module.

I already modified the graphics [`module-info`](https://github.com/elect86/openjdk-jfx/blob/develop/modules/javafx.graphics/src/main/java/module-info.java#L40-L41):
```
module javafx.graphics {
    requires java.desktop;
    requires java.xml;
    requires jdk.unsupported;
    requires org.lwjgl;
    requires org.lwjgl.opengl;
```

Added a custom repo and declared the required libs into `dependencies`, always within [`graphics`](https://github.com/elect86/openjdk-jfx/blob/develop/build.gradle#L1910-L1936)

Then I fixed step-by-step all the dependencies for `graphics` [here](https://github.com/elect86/openjdk-jfx/blob/develop/build.gradle#L2006-L2012), [here](https://github.com/elect86/openjdk-jfx/blob/develop/build.gradle#L2029) and [here](https://github.com/elect86/openjdk-jfx/blob/develop/build.gradle#L2194)

However now I'm struggling to fix the next error:

```

> Task :media:compileJava FAILED
Task ':media:compileJava' is not up-to-date because:
Task has failed previously.
All input files are considered out-of-date for incremental task ':media:compileJava'.
Compiling with Java command line compiler 'C:\Program Files\Java\jdk-11.0.1\bin\javac.exe'.
Starting process 'command 'C:\Program Files\Java\jdk-11.0.1\bin\javac.exe''. Working directory: C:\Users\elect\openjdk-jfx\modules\javafx.media Command: C:\Program Files\Java\jdk- 11.0.1\bin\javac.exe @C:\Users\elect\openjdk-jfx\modules\javafx.media\build\tmp\compileJava\java-compiler-args.txt
Successfully started process 'command 'C:\Program Files\Java\jdk-11.0.1\bin\javac.exe''
C:\Users\elect\openjdk-jfx\modules\javafx.graphics\src\main\java\module-info.java:40: error: module not found: org.lwjgl requires org.lwjgl;
^
C:\Users\elect\openjdk-jfx\modules\javafx.graphics\src\main\java\module-info.java:41: error: module not found: org.lwjgl.opengl requires org.lwjgl.opengl;
^
```

I guess I shall add lwjgl into the module path of  project `media`, but I run out of options..

I tried to modify the `media` `module-info`, the `compileJava` task, nothing.. I couldnt make it work

How may I solve it?

**Comment by kevinrushforth** [comment]
I presume you are just asking about this in the context of your own local build of OpenJFX, right? We would not accept such a dependency in the project.

The most likely source of problem is that your dependencies are not explicit modules (e.g., they need a module-info.class).

In any case, the issue tracker is probably not the best forum for asking these sort of questions. You might try the openjfx-discuss mailing list.

**Comment by elect86** [comment]
At the moment yeah, but in the long run it'd be nice if openjdx will play nice with apps using gl (or other backends)

Actually they are multi-release jars and do have `module-info.class` under `META-INF`

Ok, I'll do as you suggest, thanks
