### ISSUE TITLE
Is Cygwin actually necessary to build OpenJFX on Windows?

### ISSUE THREAD

**Issue by brcolow** [javafxports/openjdk-jfx#297]
I am setting up a new Windows PC with a fresh environment (specifically it does not have Cygwin nor WSL added to the Windows `%PATH%` environment variable).

In #276 I asked the question whether or not Cygwin was really necessary to build OpenJFX on Windows and @DeanWookey wisely noted that the only usage of it seems to be `chmod`. Looking at the source it seems this bit:

```gradle
// Need to modify file permissions Windows to make sure that the
// execute bit is set, and that the files are world readable
def chmodArtifactsSdkTask = task("chmodArtifactsSdk$t.capital", dependsOn: copyArtifactsSdkTask) {
	if (IS_WINDOWS) {
		doLast {
			exec {
				workingDir(sdkArtifactsDir)
				commandLine("chmod", "-R", "755", ".")
			}
		}
	}
}
```

is the only *hard* requirement for a Cygwin-like environment (specifically, a `chmod` binary in the `%PATH%`). A couple things to note:

1.) Simply commenting out the `exec` bit that calls `chmod` results in a working build. Is this change of permissions actually necessary if one is not running in Cygwin?
2.) I know there is quite a lot of stuff in the build files related to Cygwin (for example the `cygpath` function which is called on nearly every path) but from my testing it is *not* necessary to have Cygwin installed nor be in a Cygwin shell to build OpenJFX.
3.) Running the `tools\scripts\build.ps1` build file on a fresh Windows 10 install with only `choco` installed, and the part of the `build.ps1` script that installs Cygwin and adds it to the %PATH% commented out, the build (and all tests) succeed.

So it seems that Cygwin really is not necessary to build OpenJFX on Windows. Cygwin is a great tool, and I have used it extensively in the past, but it is a burden for new developer's setting up a Windows development environment to work on OpenJFX that we require it. Am I missing something critical/important about why Cygwin is actually required? If we can come to a consensus about it not actually being required we could change `build.ps1` to not install it, remove the call to `chmod` on Windows, change the Wiki build instructions, and maybe even remove the `cygpath` method down the line.

Thoughts?

**Comment by kevinrushforth** [comment]
We have had requests to make cygwin optional for the build in the past. As you note, it is mostly already is optional. I don't recommend changing the CI or production builds to stop using cygwin, but it would be handy for some developers if it weren't required for dev builds.

**Comment by brcolow** [comment]
Maybe we could add a `-PUSE_CYGWIN` property which defaults to true, but is set when running `tools\scripts\build.ps1`? Then we could skip the exec of `chmod` I noted in the original issue if `-PUSE_CYGWIN=false`?

**Comment by sanyarnd** [comment]
If it's Windows branch, why not to use Windows alternative to `chmod`, like [`icalcs`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls)?

**Comment by ararunprasad** [comment]
AFAIK web and media modules use some tools(make, perl, Python, ruby, gperf, bison,
..) from cygwin. Otherwise we have to install non cygwin variants of those tools.

**Comment by brcolow** [comment]
It is mostly just for local development purposes to make new Windows developers able to start hacking on this repository as painless as possible. It is not meant to be the official way to build JavaFX in any way (especially because this will be very complicated with MEDIA and WEBKIT). But because these are already excluded in the `build.ps1` file it makes sense to go just a bit in the direction Kevin mentioned. I will work on a PR.
