### ISSUE TITLE
What happened to FXML support?

### ISSUE THREAD

**Issue by Demoniaque** [javafxports/openjdk-jfx#298]
Hello, I'm new to javafx 11, I'm used to having an FXML file and using SceneBuilder, however I fail to find any trace of FXML support anymore once I updated. What happened to it and how do I use it in the new version? All the tests seem to be outdated in this repository because they're still using FXMLLoader which no longer exists.

**Comment by DJViking** [comment]
Do you have the FXML JavaFX dependency?

    compile group: 'org.openjfx', name: "javafx-fxml", version: '11', classifier: 'linux'

**Comment by Demoniaque** [comment]
I didn't know of it's existence, it should be set on the readme. thanks.
