### ISSUE TITLE
Changesets imported from mercurial has an invalid email field(devnull@localhost)

### ISSUE THREAD

**Issue by ararunprasad** [javafxports/openjdk-jfx#31]
Changesets imported from mercurial to git has an invalid email field, PSB,

    commit e8daa3be8be382c709918152fb15ff93d87e8bff
    Author: kcr <devnull@localhost>
    Date:   Tue Mar 20 13:01:33 2018 -0700

        8198654: Switch FX's default GTK version to 3
        Reviewed-by: prr

It would be better to remove the invalid email address(devnull@localhost) for futures merges.

**Comment by tiainen** [comment]
Could you please file an issue for this at the [openjdk-build repository of AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-build)? We use the scripts defined in the `git-hg` directory to mirror the official OpenJFX repository in here. As you can see for instance in https://github.com/AdoptOpenJDK/openjdk-jdk8u, they suffer from the same invalid email address:

    commit 8fb29213c6c6c13bdd2e918a8f96a981b1be7f8f
    Author: andrew <devnull@localhost>
    Date:   Fri Feb 23 05:33:43 2018 +0000

        8196952: Bad primeCertainty value setting in DSAParameterGenerator
        Summary: OpenJDK 8 applied 8072452 after 8181048, reverting parts of the latter
        Reviewed-by: coffeys
