### ISSUE TITLE
Microsoft Visual C++ Redistributable DLLs are missing from jmod

### ISSUE THREAD

**Issue by tiainen** [javafxports/openjdk-jfx#311]
The Microsoft Visual C++ Redistributable DLL files are bundled with the JavaFX SDK. They are copied explicitly in the gradle build at this point:

https://github.com/javafxports/openjdk-jfx/blob/develop/build.gradle#L4653-L4661

However, they seem to be missing from the JavaFX graphics jmod file:

    $ /opt/java11/bin/jmod list javafx-jmods-11/javafx.graphics.jmod | grep dll
    lib/decora_sse.dll
    lib/glass.dll
    lib/javafx_font.dll
    lib/javafx_iio.dll
    lib/prism_common.dll
    lib/prism_d3d.dll
    lib/prism_sw.dll

When creating a java package with `jlink` or `jpackager`, the jmods are used for inclusion into the package. The final package is then missing the MSVC++ Redistributable DLL files.

Are these DLL files left out for a specific reason or is it just an oversight?

I also notice that quite a few Windows SDK DLL files are copied as well? The same question applies to those. Should they be part of the jmod or not?

**Comment by kevinrushforth** [comment]
The Microsoft DLLs are deliberately excluded. This was done to fix [JDK-8207015](https://bugs.openjdk.java.net/browse/JDK-8207015).

**Comment by knaccc** [comment]
Please could you clarify: Does this mean that in the future, JavaFX app developers will need to instruct their users to separately download and install the Microsoft Visual C++ Redistributable?

Or, is there a way to bundle the DLLs with a jlink'd javafx app so the user does not need to do anything?
