### ISSUE TITLE
Enhance community info

### ISSUE THREAD

**Issue by bourgesl** [javafxports/openjdk-jfx#35]
Please fill the repository description as mentioned in Community guidelines:
https://github.com/javafxports/openjdk-jfx/community

**Comment by johanvos** [comment]
There are a number of default code of conduct and PR templates we can choose from.
Any preference?

**Comment by nlisker** [comment]
Both templates say the same thing as far as I can tell, and Contributor Covenant is shorter, so that's my choice.

**Comment by mikehearn** [comment]
Perhaps just avoid it. Code's of Conduct sound good but have been the cause of far more drama than they could have possibly avoided in other communities (e.g. nodejs). They seem to be an invitation for people who care more about politics than code. If OpenJFX ends up needing one it'll become apparent at the time.

**Comment by bourgesl** [comment]
Description fixed, that's good.
