### ISSUE TITLE
Calling setOnAction((ActionEvent event) -> {..} causes nullPointer

### ISSUE THREAD

**Issue by ThePfaffanater** [javafxports/openjdk-jfx#350]
In a method I have a button, that used to work perfectly in JFX on JDK8. 
On the call `setOnAction((ActionEvent event) -> {...}` when running gradle with the application plugin it spits out this repeatedly and refuses to draw anything else. 

> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.shape(PrismTextLayout.java:871)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1065)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:222)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:250)
> 	at javafx.graphics/javafx.scene.text.Text.doComputeGeomBounds(Text.java:1202)
> 	at javafx.graphics/javafx.scene.text.Text.access$300(Text.java:127)
> 	at javafx.graphics/javafx.scene.text.Text$1.doComputeGeomBounds(Text.java:148)
> 	at javafx.graphics/com.sun.javafx.scene.shape.TextHelper.computeGeomBoundsImpl(TextHelper.java:90)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
> 	at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Parent.java:1706)
> 	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1645)
> 	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
> 	at javafx.graphics/javafx.scene.Parent.access$200(Parent.java:79)
> 	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
> 	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
> 	at javafx.graphics/javafx.scene.layout.Region.access$300(Region.java:147)
> 	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
> 	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1634)
> 	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
> 	at javafx.graphics/javafx.scene.Parent.access$200(Parent.java:79)
> 	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
> 	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
> 	at javafx.graphics/javafx.scene.layout.Region.access$300(Region.java:147)
> 	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
> 	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1634)
> 	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
> 	at javafx.graphics/javafx.scene.Parent.access$200(Parent.java:79)
> 	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
> 	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
> 	at javafx.graphics/javafx.scene.layout.Region.access$300(Region.java:147)
> 	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Parent.createCachedBounds(Parent.java:1801)
> 	at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Parent.java:1664)
> 	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1645)
> 	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
> 	at javafx.graphics/javafx.scene.Parent.access$200(Parent.java:79)
> 	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
> 	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
> 	at javafx.graphics/javafx.scene.layout.Region.access$300(Region.java:147)
> 	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Node.updateBounds(Node.java:766)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1832)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1830)
> 	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2497)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 7
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
> 	at java.base/java.util.Objects.checkIndex(Objects.java:372)
> 	at java.base/java.util.ArrayList.get(ArrayList.java:458)
> 	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
> 	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
> 	at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Parent.java:1701)
> 	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1645)
> 	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
> 	at javafx.graphics/javafx.scene.Parent.access$200(Parent.java:79)
> 	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
> 	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
> 	at javafx.graphics/javafx.scene.layout.Region.access$300(Region.java:147)
> 	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
> 	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
> 	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3837)
> 	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3799)
> 	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3747)
> 	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3901)
> 	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3693)
> 	at javafx.graphics/javafx.scene.Node.updateBounds(Node.java:766)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1832)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1830)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1830)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1830)
> 	at javafx.graphics/javafx.scene.Parent.updateBounds(Parent.java:1830)
> 	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2497)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kevinrushforth** [comment]
Please provide a standalone test case that reproduce this.
