### ISSUE TITLE
Have any idea or plan about hot reload like TornadoFx or Flutter?

### ISSUE THREAD

**Issue by XQDD** [javafxports/openjdk-jfx#351]
See:
https://www.youtube.com/watch?v=HbPngSnvaWQ
https://www.youtube.com/watch?v=1UZ6686QsOw

**Comment by johanvos** [comment]
This is something you should ask at openjfx-discuss@openjdk.java.net (it's not an issue or feature for OpenJFX itself)
I'd be glad to give my thoughts on that mailinglist.
