### ISSUE TITLE
TextField styling issues (-fx-text-fill only works with :focused)

### ISSUE THREAD

**Issue by jlnr** [javafxports/openjdk-jfx#364]
We are seeing wrong text colors in some text fields after upgrading from JDK 8 to OpenJDK 11 with the javafx-sdk-11.0.1.

The text has the right color as long as the text field has the focus, but it turns black as soon as the focus moves to another text field.

The issue can be worked around by setting another pseudoclass when `:focused` is being removed.

To reproduce, run the following program, and notice that both text fields behave differently — I think they shouldn't.

```java
import javafx.application.Application;
import javafx.css.PseudoClass;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class JFX11TextField extends Application {

    private static final PseudoClass WORKAROUND = PseudoClass.getPseudoClass("workaround");

    @Override
    public void start(Stage primaryStage) {
        Application.setUserAgentStylesheet("main.css");

        // The text in this text field should be red, even when it does not have the focus.
        TextField brokenTextField = new TextField();

        // The text in this text field is always red thanks to this :workaround.
        TextField workaroundTextField = new TextField();
        workaroundTextField.focusedProperty().addListener(observable ->
            workaroundTextField.pseudoClassStateChanged(WORKAROUND, !workaroundTextField.isFocused()));

        primaryStage.setScene(new Scene(new VBox(brokenTextField, workaroundTextField)));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

main.css:

```css
.text-field, .text-field:focused, .text-field:workaround { -fx-text-fill: red; }
```

**Comment by sghpjuikit** [comment]
I am also facing this strange issue.

I only encountered it for content within popups, which have hard to understand focus behavior to begin with and the issue nehaves erratically - it depends on whether any focusable parent of the text field has focus and it also depends on the order the text field/owner is focused - I think.

Your workaround worked for me. Better than nothing. Thx.

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com).

If you are interested in contributing a fix for this issue, please see [CONTRIBUTING.md](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md) in the official [openjdk/jfx](https://github.com/openjdk/jfx) GutHub repo.
