### ISSUE TITLE
Are there official 32-bit builds?

### ISSUE THREAD

**Issue by graynk** [javafxports/openjdk-jfx#376]
I couldn't find anywhere the links for 32-bit builds for Windows. Do I have to build manually with 32-bit JDK?

**Comment by graynk** [comment]
[openjfx11_x86.zip](https://github.com/javafxports/openjdk-jfx/files/2860187/openjfx11_x86.zip)

I've built my own (without media and webkit) in case anyone needs them, but I still feel there should be official 32-bit binaries, since there are 32-bit builds of OpenJDK11 (AdoptOpenJDK, Liberica), even if Oracle doesn't provide them.

**Comment by kevinrushforth** [comment]
Our current build setup uses Oracle's OpenJDK builds from jdk.java.net so it would require a special setup and additional work to support 32-bit builds. I'm skeptical that it is worth the effort, but @johanvos comment on whether he is interested in considering this.

**Comment by johanvos** [comment]
We have a win 32 bit version of JavaFX 11 at https://drive.google.com/open?id=1wx9009v1mkmN6v72p3I7vruaBTIVNdAg but we don't support it at the moment.
At this point, the focus is at delivering high-quality, supported versions for Linux/Mac/Windows 64 bit.

We will support more architectures/OS'es in the future, but that will be mainly based on demand and my feeling is that there is not much commercial interest in win32 at the moment.

Creating a bundle is easy, but maintaining a product like JavaFX for a given OS/arch is by no means trivial, and it requires a fair amount of resources to support it -- hence we can only do that if there is enough commercial interest.

**Comment by graynk** [comment]
> Creating a bundle is easy, but maintaining a product like JavaFX for a given OS/arch is by no means trivial

What does this imply for me? What are some of the things that could go wrong if I use the bundle that I've built for 32-bit OS due to the lack of support? Or is it safe to use for now (due to the legacy of JavaFX 8), but it may break at some point in the future when some feature gets added?

**Comment by johanvos** [comment]
(disclaimer: I am now a lawyer and I don't talk about legal implications).
I think it's totally ok you're using this build for your projects. 
As you say, if new features are added in later versions of JavaFX, they can't be used in your build of course. 
If bugfixes are backported to 11, they will be in supported builds, but not in your builds. 

But if you control the environment your build will be used in, and you deal with user requests/issues, I don't see a problem.

**Comment by mkpaz** [comment]
I've asked the same [question on SO](https://stackoverflow.com/questions/54179851/openjfx-support-for-32-bit-systems). Could you please mention that OpenJFX11 32-bit build exists and can be downloaded from GDrive on the [official wiki page](https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX) too.

Also I think that OpenJFX 32-bit build for Windows totally makes sense because OpenJFX is a desktop platform. While any server nowadays has more than 4Gb RAM the same thing can't be said about enterprise workstations. Typically most companies do not upgrade hardware until they really have to. Moreover, Win7 will be supoported until 01/2020, Win8 until 01/23 and Win10 has 32-bit version too.

**Comment by sonnenhohl** [comment]
> 
> 
> I've asked the same [question on SO](https://stackoverflow.com/questions/54179851/openjfx-support-for-32-bit-systems). Could you please mention that OpenJFX11 32-bit build exists and can be downloaded from GDrive on the [official wiki page](https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX) too.
> 
> Also I think that OpenJFX 32-bit build for Windows totally makes sense because OpenJFX is a desktop platform. While any server nowadays has more than 4Gb RAM the same thing can't be said about enterprise workstations. Typically most companies do not upgrade hardware until they really have to. Moreover, Win7 will be supoported until 01/2020, Win8 until 01/23 and Win10 has 32-bit version too.

In our company we also deploy desktop applications with JavaFX, now that we are migrating to JDK 11 we are facing some challenges, creating desktop apps only for x64  is not an option for us since many computers still run on x86.

**Comment by graynk** [comment]
> In our company we also deploy desktop applications with JavaFX, now that we are migrating to JDK 11 we are facing some challenges, creating desktop apps only for x64 is not an option for us since many computers still run on x86.

Yup, I'm in exactly the same boat. So while I understand the reasoning behind not supporting 32-bit, I'm not entirely sure who's the target audience then. What would you use JavaFX for, if not for desktop apps? (Well, we use it for embedded as well, but it's far, far from ideal choice for that as well, given the performance).

**Comment by sonnenhohl** [comment]
@graynk I'm working on compiling it on Windows for 32 bits, if it works i can create a repo and share those compiled versions, and maybe someone get interested and helps into updating for future releases.

Right now i'm facing this issue: https://github.com/javafxports/openjdk-jfx/issues/389

**Comment by graynk** [comment]
> @graynk I'm working on compiling it on Windows for 32 bits, if it works i can create a repo and share those compiled versions, and maybe someone get interested and helps into updating for future releases.
> 
> Right now i'm facing this issue: #389

In the second post there're my compiled versions without media and web, and later down the line there's a link to dropbox with internal compiled versions as well. 
Judging by your error you've set up environment variables incorrectly, since it's looking for "MSVC/14.11.25503/" in its path, when you've said that you have 14.13.26128

**Comment by sonnenhohl** [comment]
> 
> 
> [openjfx11_x86.zip](https://github.com/javafxports/openjdk-jfx/files/2860187/openjfx11_x86.zip)
> 
> I've built my own (without media and webkit) in case anyone needs them, but I still feel there should be official 32-bit binaries, since there are 32-bit builds of OpenJDK11 (AdoptOpenJDK, Liberica), even if Oracle doesn't provide them.

I'm testing your build its working fine on Windows 10 but isn't working on Windows 7 x86, the error is:

WARNING [org.netbeans.core.windows.WindowManagerImpl]
java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.swing/javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
[catch] at java.base/java.lang.Thread.run(Thread.java:834)
GraphicsPipeline.createPipeline failed for com.sun.prism.d3d.D3DPipeline
java.lang.UnsatisfiedLinkError: C:\WEG\WPS 2.43\wps\modules\jre\bin\prism_d3d.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at javafx.graphics/com.sun.prism.d3d.D3DPipeline.lambda$static$0(D3DPipeline.java:48)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.prism.d3d.D3DPipeline.<clinit>(D3DPipeline.java:44)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javafx.graphics/com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
*** Fallback to Prism SW pipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: C:\WEG\WPS 2.43\wps\modules\jre\bin\prism_sw.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at javafx.graphics/com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javafx.graphics/com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.swing/javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Diagnostic information
Input arguments:
	-Xverify:none
	-Xms320m
	-Dapple.laf.useScreenMenuBar=true
	-Duser.language=en
	-Duser.country=US
	-Dprism.verbose=true
	-Xmx1024m
	-Dnetbeans.user.dir=C:\WEG\WPS 2.43\bin
	-Djdk.home=wps/modules/jre
	-splash:C:\Users\arturs\AppData\Roaming\.wps\2.43\var\cache\splash.png
	-Dnetbeans.home=C:\WEG\WPS 2.43\platform
	-Dnetbeans.user=C:\Users\arturs\AppData\Roaming\.wps\2.43
	-Dnetbeans.default_userdir_root=
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\arturs\AppData\Roaming\.wps\2.43\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Dnetbeans.dirs=C:\WEG\WPS 2.43\wps;C:\WEG\WPS 2.43\extide;C:\WEG\WPS 2.43\harness;C:\WEG\WPS 2.43\ide;C:\WEG\WPS 2.43\java
	exit
Compiler: HotSpot Tiered Compilers
Heap memory usage: initial 320.0MB maximum 1024.0MB
Non heap memory usage: initial 160.0kB maximum -1b
Garbage collector: G1 Young Generation (Collections=7 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=9033 total loaded=9033 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 3,666,391,040
INFO [null]: Total physical memory 3,666,391,040
WARNING [org.openide.filesystems.Ordering]: Found same position 50 for both Menu/Window/ShowPaletteAction.shadow and Menu/Window/VariablesAction.shadow
WARNING [org.openide.filesystems.Ordering]: Found same position 1 for both Menu/Window/net-weg-wps-ethernetmemorytrend-EthTrendTopComponent.shadow and Menu/Window/org-netbeans-core-windows-actions-ToolbarsListAction.shadow
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/Window/ marked with the position attribute: [org-netbeans-modules-notifications-NotificationCenterTopComponent.shadow], but some are: [net-weg-wps-ethernetmemorytrend-EthTrendTopComponent.shadow, org-netbeans-core-windows-actions-ToolbarsListAction.shadow, ShowEditorOnlyAction.shadow, ToggleFullScreenAction.shadow, Separator110.instance, ShowPaletteAction.shadow, VariablesAction.shadow, org-netbeans-modules-project-ui-logical-tab-action.shadow, org-netbeans-modules-favorites-View.shadow, net-weg-wps-wpsconfigurationprojectsupport-dialogs-ReplaceTopComponent.shadow, org-netbeans-modules-tasklist-ui-TaskListAction.shadow, org-netbeans-modules-tasks-ui-DashboardTopComponent.shadow, org-netbeans-core-io-ui-IOWindowAction.shadow, SwitchToRecentDocumentAction.shadow, Separator3.instance, ConfigureWindow, org-netbeans-core-windows-actions-ResetWindowsAction.shadow, Separator4.instance, CloseWindowAction.shadow, CloseAllDocumentsAction.shadow, CloseAllButThisAction.shadow, GroupsMenuAction.shadow, DocumentsAction.shadow]

Any ideas?

**Comment by johanvos** [comment]
That sounds like you're missing native libraries (for both es2 and sw), or that those libraries are built for the wrong architecture.
If you run with -Dprism.verbose=true you should get more detailed output.

**Comment by sonnenhohl** [comment]
@johanvos I tried now into a Win7 x64 and the same problem happens i also tried to disable prism with -Dprism.order=j2d and the error was then whit the glass.dll. Maybe if i compare the dlls present into the JRE 8 with JRE 11? Does it makes some sense for you?

**Comment by graynk** [comment]
> java.lang.UnsatisfiedLinkError: C:\WEG\WPS 2.43\wps\modules\jre\bin\prism_d3d.dll: Can't find dependent libraries
> GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
> java.lang.UnsatisfiedLinkError: C:\WEG\WPS 2.43\wps\modules\jre\bin\prism_sw.dll: Can't find dependent libraries

It seems to be missing prism dlls. Now, it __should__ work on Win7 SP1 out of the box, if you have all proper updates installed, however you can make it work even on retail version from 2009 (pure JavaFX app works for me with all the bells and whistles, didn't try Swing interop though). All the dlls that you need are in `bin` directory of SDK.

**Comment by johanvos** [comment]
For the 64 bit windows builds, we add some libraries. @kevinrushforth or @tiainen have more knowledge about what libraries and why -- and you can copy those to your 32 bit bundle too.

In general, if you have D3D on your system, selecting j2d is not a good idea.

**Comment by graynk** [comment]
> 
> 
> For the 64 bit windows builds, we add some libraries. @kevinrushforth or @tiainen have more knowledge about what libraries and why -- and you can copy those to your 32 bit bundle too.

You can't copy native libraries from 64 JDK, though. They're 64-bit as well and won't run on 32-bit OS, I've tried (and checked them with dependency walker). However, compiling OpenJFX with 32-bit JDK does compile 32-bit dlls. They're in the bin directory of compiled SDK, as stated in my previous post.

**Comment by sonnenhohl** [comment]
> 
> 
> > For the 64 bit windows builds, we add some libraries. @kevinrushforth or @tiainen have more knowledge about what libraries and why -- and you can copy those to your 32 bit bundle too.
> 
> You can't copy native libraries from 64-bit build of OpenJFX though. They're 64-bit as well and won't run on 32-bit OS, I've tried (and checked them with dependency walker). However, compiling OpenJFX with 32-bit JDK does compile 32-bit dlls. They're in the bin directory of compiled SDK, as stated in my previous post.

I created a JRE using jlink with adoptjdk 32 and with jmods of your sdk from the zip.

**Comment by sonnenhohl** [comment]
> 
> 
> For the 64 bit windows builds, we add some libraries. @kevinrushforth or @tiainen have more knowledge about what libraries and why -- and you can copy those to your 32 bit bundle too.
> 
> In general, if you have D3D on your system, selecting j2d is not a good idea.

Those libraries are 32-bit or 64-bit independent?

**Comment by graynk** [comment]
> I created a JRE using jlink with adoptjdk 32 and with jmods of your sdk from the zip.

I use jlink too (on Liberica JDK, though that shouldn't matter). All dlls still must be present beside java.exe in bin directory of resulting JRE (and they are for me, though I don't remember anymore if I copied them manually). Check if they're there, if not, try copying them over from SDK.

> Those libraries are 32-bit or 64-bit independent?

They're definitely 64-bit. You can check with [dependency walker](http://dependencywalker.com/) for yourself.

**Comment by johanvos** [comment]
> You can't copy native libraries from 64-bit build of OpenJFX though. They're 64-bit as well and won't run on 32-bit OS, I've tried (and checked them with dependency walker).

Absolutely true.  When I said "copy" I meant copy the files from the MSVC or Windows libraries into your bundle (not from the 64 bit bundle into the 32 bit bundle).

**Comment by sonnenhohl** [comment]
@graynk I downloaded your build again from https://github.com/javafxports/openjdk-jfx/files/2860187/openjfx11_x86.zip, i replaced all the dlls into the jre folder but still isn't running on Win7 x86 or Win7 x64, but is running on Windows 10 x86 and x64. I think is more related with what @johanvos said about windows libraries, know i just need to discover which are those libraries.

**Comment by graynk** [comment]
> Absolutely true. When I said "copy" I meant copy the files from the MSVC or Windows libraries into your bundle (not from the 64 bit bundle into the 32 bit bundle).

Ah, sorry, I misinterpreted you.

> I think is more related with what @johanvos said about windows libraries, know i just need to discover which are those libraries.

These __are__ the missing libraries though. All I can state with certainty is that error message indicates that it can't find these exact libraries, and that this build works for me on multiple machines, both 32-bit and 64-bit, as well as in VirtualBox, on multiple versions of Windows 7, fresh installs and not. Can't help you any more than that, sorry.

**Comment by kevinrushforth** [comment]
The logic in `build.gradle` and `buildSrc/win.gradle` will copy the Microsoft executables from either the 32-bit or 64-bit DLLs from MSVC depending on what architecture you are building for. I presume that you are using a 32-bit boot JDK to build, which is how the FX build selects which architecture to use (32-bit or 64-bit).

You may also need to set the `MSVC_VER` and `MSVC_REDIST_VER` gradle properties (e.g., with `gradle -PMSVC_VER=... -PMSVC_REDIST_VER=...`) to match your installation of VS2017. 

Once you have a build, to see whether they are being loaded you can run `java -Djavafx.verbose=true ...`

**Comment by kevinrushforth** [comment]
And so you don't drive yourself crazy chasing phantom bugs....

1. Stop the gradle daemon (or don't use it at all)
2. Run `gradle clean` by itself, prior to rebuilding, if you are going to change any of the properties like `MSVC_VER`

**Comment by sonnenhohl** [comment]
@kevinrushforth I'm unable to compile it on my Windows 10 machine (https://github.com/javafxports/openjdk-jfx/issues/389), so im using the build created by @graynk but it is working only on Windows 10 x86 and Windows 10x64 but not on Win 7 x86 and x64. The error that happens on windows 7 is java.lang.UnsatisfiedLinkError: C:\WEG\WPS 2.43\wps\modules\jre\bin\prism_d3d.dll: Can't find dependent libraries but the files are in the right folder since they are loading on Win 10.

**Comment by kevinrushforth** [comment]
> im using the build created by @graynk but it is working only on Windows 10 x86 and Windows 10x64 but not on Win 7 x86 and x64.

Then that build is incomplete. It is missing the copying of the Microsoft DLLs, as @johanvos and I said above.

> What libraries prism_d3d.dll are dependent on? That are on Win10 but not on Win7?

The Microsoft redistributable libraries (from VS2017 and the Windows 10 SDK). There are 44 of them:

```
api-ms-win-*  [40]
concrt140.dll
msvcp140.dll
vcruntime.dll
```

**Comment by sonnenhohl** [comment]
I found the missing libraries which are: msvcp140.dll, vcruntime140.dll and concrt140.dll after getting those libraries from Windows 10 x86 now it is working on Windows 7.

Many thanks @kevinrushforth @johanvos @graynk

**Comment by Bodyash** [comment]
Need x86 builds for linux, can't find it.

**Comment by Glavo** [comment]
Zulu currently provides 32-bit jdk 11 with OpenJFX 11 for Linux and Windows: [ZuluFX](https://www.azul.com/downloads/zulu-community/?&architecture=x86-32-bit&package=jdk-fx), it works well.

**Comment by graynk** [comment]
> Zulu currently provides 32-bit jdk 11 with OpenJFX 11 for Linux and Windows: [ZuluFX](https://www.azul.com/downloads/zulu-community/?&architecture=x86-32-bit&package=jdk-fx), it works well.

I totally forgot about this issue. I prefer [Bellsoft](https://bell-sw.com/pages/java-13.0.1/) now, but Zulu works too.
