### ISSUE TITLE
scroll events finish with wrong delta's on mac: JDK-8183399

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#38]
see https://bugs.openjdk.java.net/browse/JDK-8183399

**Comment by johanvos** [comment]
I could reproduce it, and found out why this happens.
The relevant events are sent to GlassViewDelegate.m sendJavaMouseEvent:(NSEvent *)theEvent

That method then uses the [theEvent deltaX] and [theEvent deltaY] and pass those to the Java layer unless they are 0.
I could observe these values, in the end, become 0 a number of times, and only after e.g. 3 0 values, the cumulative value was high enough to be passed.

I changed the [theEvent deltaX] to [theEvent scrollingDeltaX] and similar for Y, and that always return non-0 values, that gradually decrease as one should expect.

**Comment by johanvos** [comment]
The following patch could fix this:
```
--- a/modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m
+++ b/modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m
@@ -425,8 +425,9 @@ - (void)sendJavaMouseEvent:(NSEvent *)theEvent
     jdouble rotationY = 0.0;
     if (type == com_sun_glass_events_MouseEvent_WHEEL)
     {
-        rotationX = (jdouble)[theEvent deltaX];
-        rotationY = (jdouble)[theEvent deltaY];
+        rotationX = (jdouble)[theEvent scrollingDeltaX];
+        rotationY = (jdouble)[theEvent scrollingDeltaY];
+
 
         //XXX: check for equality for doubles???
         if (rotationX == 0.0 && rotationY == 0.0)

```

**Comment by dlemmermann** [comment]
This only seems to fix it for the mouse wheel. How about gestures?

**Comment by dlemmermann** [comment]
And also only on Mac. Aren‘t other operating systems affected?

**Comment by johanvos** [comment]
It is not mouse wheel specific (I tested it with gestures). It's a mac-only issue indeed. It is in the native-glass layer, and the wrong values are passed to the java layer.

**Comment by johanvos** [comment]
The values of scrollingDeltaX/Y are 10 times higher than the ones of deltaX/Y.
The native events are sent to the Java layer (MacGestureSupport.scrollGesturePerformed) and then forwarded to e.g. GestureSupport.handleScrollingPerformed where a multiplier (hard-coded to 10) is passed as well.
Using the scrollingDeltaX/Y values instead of deltaX/Y values, this multiplier can be set to 1.

If we can't touch MacGestureSupport, we can still fix the issue by dividing the scrollingDeltaX/Y by 10 before passing to the Java layer.

A similar issue seems to be reported on AWT: https://bugs.openjdk.java.net/browse/JDK-8173876

**Comment by mipastgt** [comment]
I am wondering whether this bug (and the fix) are also related to this bug. https://bugs.openjdk.java.net/browse/JDK-8095155
