### ISSUE TITLE
JDK-8220396: Bindings class gives a lot of unneeded 'select-binding' log messages

### ISSUE THREAD

**Issue by mipastgt** [javafxports/openjdk-jfx#383]
JavaFX still spits out too many false warnings in case you use select-binding
and you have a dynamic model with many properties that can be set to null from time to time.
This is completely normal behaviour and should not cause any warnings at all. It is just annoying
and clutters your log-files so that you do not see real warnings anymore between all that garbage.

This issue was already addressed a long time ago in

https://bugs.openjdk.java.net/browse/JDK-8097814

but was not solved completely. You still get lots of warnings like this:

Feb. 20, 2019 10:43:05 VORM. com.sun.javafx.binding.SelectBinding$SelectBindingHelper getObservableValue
WARNING: Exception while evaluating select-binding [viewport]

The problem is here in SelectBinding$SelectBindingHelper.getObservableValue():

	} catch (RuntimeException ex) {
		final PlatformLogger logger = Logging.getLogger();
		if (logger.isLoggable(Level.WARNING)) {
			Logging.getLogger().warning("Exception while evaluating select-binding " + stepsToString());
			if (ex instanceof  IllegalStateException) {
				logger.warning("Property '" + propertyNames[i] + "' does not exist in " + obj.getClass(), ex);
			} else if (ex instanceof NullPointerException) {
				logger.fine("Property '" + propertyNames[i] + "' in " + properties[i] + " is null", ex);
			} else {
				Logging.getLogger().warning("", ex);
			}
		}
		// return default
		updateDependencies();
		return null;
	}

This should be changed to:

	} catch (RuntimeException ex) {
		final PlatformLogger logger = Logging.getLogger();
		if (logger.isLoggable(Level.WARNING)) {
			String msg = "Exception while evaluating select-binding " + stepsToString();
			if (ex instanceof  IllegalStateException) {
				logger.warning(msg);
				logger.warning("Property '" + propertyNames[i] + "' does not exist in " + obj.getClass(), ex);
			} else if (ex instanceof NullPointerException) {
				logger.fine(msg);
				logger.fine("Property '" + propertyNames[i] + "' in " + properties[i] + " is null", ex);
			} else {
				logger.warning(msg, ex);
			}
		}
		// return default
		updateDependencies();
		return null;
	}

I extracted the common message into a String and then moved the actual logging into
the if-block which handles the different exception types so that the logging of the
common message happens with the same level as the rest of the logging for this
exception type. In addition I replaced some useless references to Logging.getLogger()
with just logger because we have that already. Furthermore I combined the log output
of the else branch into a single logger call because having two separate ones does
not seem to be reasonable in this case.

Here is a little test program to show the behavior:
[BindingsEval.java.zip](https://github.com/javafxports/openjdk-jfx/files/2953462/BindingsEval.java.zip)

**Comment by hjohn** [comment]
Seeing exactly the same problem.  It's really confusing, because in the log you now see `Exception while evaluating select-binding [xxx]`, but the log record has no exception attached to it for the case where it just involves a `null` value (in which case the entire message should have been logged at the `fine` level.  The fix seems spot on.

**Comment by kevinrushforth** [comment]
@hjohn if either you ot @mipastgt would like to pursue this, please file a bug in JBS

**Comment by mipastgt** [comment]
I have filed that bug in JBS already in March and also updated it with some example code

https://bugs.openjdk.java.net/browse/JDK-8220396

and I see you Kevin as the assignee in it :-)

**Comment by kevinrushforth** [comment]
Good to know! 

I was cleaning up some GitHub issues, and it didn't click that this was already filed. :)

**Comment by mipastgt** [comment]
Hi, I just want to ask whether there is any chance that this might make it into 13.
Thanks
Michael

**Comment by kevinrushforth** [comment]
> Hi, I just want to ask whether there is any chance that this might make it into 13.

No, this isn't going to make JavaFX 13. I note that it isn't targeted to any particular release (fixVersion=tbd), so it's unlikely to make JavaFX 14, either, unless someone in openjfx-dev community wants to take it up an contribute a fix. We would need a unit test along with the fix.

**Comment by mipastgt** [comment]
What kind of additional unit tests would you expect here? The proposed fix does not change any functionality. It just avoids an unneeded warning message. The existing tests should be sufficient to ensure that no functionality has been changed accidentally.

**Comment by kevinrushforth** [comment]
What I had imagined was a unit test that sets up a logger (we have other tests that do this) and generates a null select-binding and verifies no log message (this one would fail today and pass with a fix), and also verifies that other messages are still logged.

> The existing tests should be sufficient to ensure that no functionality has been changed accidentally.

Fair enough. I would be willing to take a fix without this as long as there was a standalone test program that showed correct behavior after the fix.

**Comment by kevinrushforth** [comment]
Btw, if you would like to contribute a fix, please see [CONTRIBUTING.md](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md).

**Comment by mipastgt** [comment]
Would the standalone test program, which I already provided at the end of the issue description above in february, https://github.com/javafxports/openjdk-jfx/files/2953462/BindingsEval.java.zip fit your needs? As far as I have understood you, it does exactly what you want. It gives a lot of warnings before the fix and should be quiet after the fix. If yes, I could prepare a PR over the weekend. And just in case this would be your next question: I have signed the OCA already a long time ago :-)

**Comment by kevinrushforth** [comment]
> Would the standalone test program, which I already provided at the end of the issue description above in february

That does half of what I want to see. The other half is to ensure that the warnings that are *not* NPE are still logged after your proposed fix.

> I could prepare a PR over the weekend. And just in case this would be your next question: I have signed the OCA already a long time ago

Sounds good. I'll just need to verify your OCA and then we are all set.

**Comment by kevinrushforth** [comment]
> Would the standalone test program, which I already provided at the end of the issue description above in february

That does half of what I want to see. The other half is to ensure that the warnings that are *not* NPE are still logged after your proposed fix.

> I could prepare a PR over the weekend. And just in case this would be your next question: I have signed the OCA already a long time ago

Sounds good. I'll just need to verify your OCA and then we are all set.

**Comment by kevinrushforth** [comment]
> I'll just need to verify your OCA and then we are all set.

OK, I just confirmed this.

**Comment by kevinrushforth** [comment]
Pushed.

**Comment by mipastgt** [comment]
Hi Kevin
Many thanks for pushing this.
I will now close this issue here.
