### ISSUE TITLE
JDK-8219734: WebKit uses macOS private API, which casues AppStore rejection

### ISSUE THREAD

**Issue by yososs** [javafxports/openjdk-jfx#388]
> Found private symbol usage.
> Symbols: _CCRandomCopyBytes, _kCCRandomDefault, __NSConcreteMallocBlock
> From framework: /usr/lib/libSystem.B.dylib
> In binary: Contents/PlugIns/Java.runtime/Contents/Home/jre/lib/libjfxwebkit.dylib

I just started the investigation, but the next patch is considered to be helpful.

* https://github.com/NativeScript/ios-runtime/issues/991
* https://github.com/NativeScript/ios-runtime/pull/992/commits/bffd5a8eb0656364ab5bcb8db87038752c04cc66

The linked symbol list is obtained with the following command.

`llvm-nm -u libjfxwebkit.dylib`

**Comment by johanvos** [comment]
At first sight, this has been in our webkit drop since at least the release of JavaFX 11 but I didn't hear about Apple rejections before. If it is indeed the reason for rejection, we have to remove the usage of those symbols indeed (conditionally).

**Comment by kevinrushforth** [comment]
I wonder if Apple recently added this to their list of rejected symbols, or if we've been broken since JavaFX 11?

**Comment by ararunprasad** [comment]
We may need to cherry pick the following change, which switches to API instead of SPI.,

https://trac.webkit.org/changeset/237721/webkit

**Comment by kevinrushforth** [comment]
@ararunprasad That sounds good. Can you file a JBS bug for this?

**Comment by ararunprasad** [comment]
JBS link: https://bugs.openjdk.java.net/browse/JDK-8219734

**Comment by ararunprasad** [comment]
And an another fix from NativeScript port of WebKit to get rid of `__NSConcreteMallocBlock` usage,

https://github.com/NativeScript/webkit/commit/80b68c0238e02376c357af17267ac8443fb100c5

**Comment by kevinrushforth** [comment]
> do you have any objection to cherry pick the above one from NativeScript?

We can't take it directly from that project. It would be unapproved third-party code (and with no license terms). If it hasn't been contributed back to WebKit we will need to apply our own patch.
