### ISSUE TITLE
JavaDocs hosting

### ISSUE THREAD

**Issue by eugener** [javafxports/openjdk-jfx#39]
Starting with Java 11, JavaFX would be distributed separately. We have to come up with the way to host latest JavaDocs for production releases as well as snapshots

**Comment by eugener** [comment]
It might be possible to host it here on GitHub as a separate repository, where master can serve as a production release site and branches as different snapshots, but that does not solve the issue of having permalinks to previous releases. Ideas?

**Comment by hendrikebbers** [comment]
We can use GitHub pages to host the javadoc. I'm doing the same here for example: https://canoo.github.io/dolphin-platform/javadoc/core/

Just an additional step in travis: https://github.com/canoo/dolphin-platform/blob/master/.travis.yml

**Comment by anidotnet** [comment]
@eugener if you consider using external site to host javadoc other than github, all you have to do is publish the javadoc jar in maven central and access the javadoc from https://javadoc.io . They maintains javadoc for each version. Here is one example - https://javadoc.io/doc/org.dizitart/nitrite/2.1.1

**Comment by DJViking** [comment]
What of the JavaFX CSS Reference?
https://docs.oracle.com/javase/10/docs/api/javafx/scene/doc-files/cssref.html

**Comment by eugener** [comment]
Closing this one. 
I opened a separate issue #213 for CSS Reference hosting
