### ISSUE TITLE
Cannot start application (WinLauncher) if path contains non-ascii character

### ISSUE THREAD

**Issue by overheadhunter** [javafxports/openjdk-jfx#400]
I want to add a comment to [JDK-8205991](https://bugs.openjdk.java.net/browse/JDK-8205991) but since the JBS is a pretty exclusive club, I can't. Since OpenJFX is supposedly aiming to be developed in a more open fashion, I hope by creating this issue, my comment finds its way to the right people.

According to @kevinrushforth the issue won't be fixed since the the packager will be reworked in JEP 343 anyway (which seems like the right decision for me). However, I can reproduce the issue with Oracle JDK 8u201. This is a regression somewhere after 8u144. Probably due to a backport from JDK 10.

**Comment by kevinrushforth** [comment]
Thanks for the information. The replacement tool for `javapackager`, `jpackage`, is being developed independently of JavaFX, but I'll add your comment to the bug report for [JDK-8205991](https://bugs.openjdk.java.net/browse/JDK-8205991).
