### ISSUE TITLE
Security Vulnerability Reported with no Response

### ISSUE THREAD

**Issue by JLLeitschuh** [javafxports/openjdk-jfx#419]
I responsibly disclosed a security vulnerability in this project to the email vuln-report@openjdk.java.net on Mon, Feb 25, 3:31 PM and haven't received a response. Just following up to ensure that it was actually received. If there is a different email I should have contacted, please let me know where I should send the report.

**Comment by kevinrushforth** [comment]
That email address is not yet active.

Please see the following page to report a security vulnerability:

https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html

**Comment by JLLeitschuh** [comment]
@kevinrushforth I just forwarded the email to that address. Thank you.
