### ISSUE TITLE
JDK-8221941: Wrong package declaration for WCTextRunImpl.java in web module

### ISSUE THREAD

**Issue by nlisker** [javafxports/openjdk-jfx#425]
https://github.com/javafxports/openjdk-jfx/blob/b57d25ed5f754445ca9d929bdf8111aa5d6c0d39/modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCTextRunImpl.java#L26

Eclipse is reporting that the above file has the wrong package declaration, and it seems to be correct since it is located under `com.sun.javafx.webkit.prism`. The class `com.sun.javafx.webkit.prism.WCFontImpl` is also using it in `import com.sun.webkit.graphics.WCTextRunImpl;`, which generates an error.

@ararunprasad can you take a look please?

**Comment by kevinrushforth** [comment]
Yeah, this looks wrong to me. I'm surprised other tools haven't run into problems before now.

**Comment by nlisker** [comment]
Yeah, I just ran a gradle build successfully and I don't understand how it didn't pick it up.

**Comment by kevinrushforth** [comment]
I filed [JDK-8221941](https://bugs.openjdk.java.net/browse/JDK-8221941) in JBS to track this.

**Comment by kevinrushforth** [comment]
Fixed by https://bugs.openjdk.java.net/browse/JDK-8221941
