### ISSUE TITLE
Change version to 12 on https://openjfx.io

### ISSUE THREAD

**Issue by TimurJD** [javafxports/openjdk-jfx#426]
On the https://openjfx.io we can see it's still JavaFX 11 while the new version is 12. Maybe it would be good to update it?!

**Comment by odbuser2** [comment]
I agree it probably needs clarification but it may be that way since 11 is LTS.

**Comment by nlisker** [comment]
The patch to fix it is currently under review at https://github.com/openjfx/openjfx.github.io/pull/10.

**Comment by TimurJD** [comment]
@nlisker now it's JavaFX 12, thanks.

**Comment by nlisker** [comment]
Yeah, it was merged a few hours ago. You can close this issue, unless you want it to include the ["Getting Started" pages](https://openjfx.io/openjfx-docs/), which are in a different repo.

**Comment by TimurJD** [comment]
It would be nice to have it in consistent state. @nlisker is it hard to fix it in the repo?

**Comment by johanvos** [comment]
The getting started pages are in https://github.com/openjfx/openjfx-docs
