### ISSUE TITLE
remove dependencies on internal API's of core modules

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#43]
At this moment, it is not possible to build the JavaFX modules with a JDK that doesn't have JavaFX as bootJDK.
The following issue on JBS tracks this: https://bugs.openjdk.java.net/browse/JDK-8195798

In particular, the following issue tracks the removal of the dependencies on the internal logging API:
https://bugs.openjdk.java.net/browse/JDK-8195799

Reviewing this code is highly encouraged.

**Comment by johanvos** [comment]
The umbrella issue for this is https://bugs.openjdk.java.net/browse/JDK-8195798

**Comment by kevinrushforth** [comment]
By way of cleanup, I note that since https://bugs.openjdk.java.net/browse/JDK-8195798 is resolved, this issue can be closed, too.
