### ISSUE TITLE
This is a bad place for this question but ...

### ISSUE THREAD

**Issue by Maybelater2019** [javafxports/openjdk-jfx#432]
Will JavaFX be added back to the Java JDK? I think it's a lot better than downloading it shared. What do you say? Do you find it much better if it's already inside the Java JDK?

**My opinion: I find it much better if JavaFX is already in the Java JDK.**

**Comment by dlemmermann** [comment]
It will not be added back.
Yes this is the wrong place for this question. 
I find it much better that JavaFX can evolve on its own. 
Before anybody else wastes time on this ticket I would like to ask @johanvos to close it.

**Comment by ChristianLP1** [comment]
I think it's a lot better when it's together ... Unfortunately, it happened.

**Comment by Maybelater2019** [comment]
Thanks for you opinion. :)

**Comment by kevinrushforth** [comment]
1. There are no current plans to ship JavaFX with the JDK 11 or later
2. This issue tracker isn't the right place to ask these sort of questions anyway.

**Comment by JavaFX-Fan** [comment]
Sad to hear that!
