### ISSUE TITLE
Dropdown of combobox does not get scaled

### ISSUE THREAD

**Issue by mj-p** [javafxports/openjdk-jfx#443]
When a combobox is scaled using setScaleX/Y its dropdown menu is not scaled at all.

Seems to be a known issue for quite some time:
[https://bugs.openjdk.java.net/browse/JDK-8130378](https://bugs.openjdk.java.net/browse/JDK-8130378)

**Comment by kevinrushforth** [comment]
There is no need to open a GitHub issue unless you have additional information to share.
