### ISSUE TITLE
JavaScript onclick, onmouseover and onmouseout don't work with SVG Line Elements (JDK-8161284)

### ISSUE THREAD

**Issue by jimbok8** [javafxports/openjdk-jfx#444]
I should like to report the bug outlined in JDK-8161284, which I believe is still not fixed (please correct me if I am wrong!)
"JavaScript onclick, onmouseover and onmouseout don't work with SVG Line Elements"

Test code and .svg file attached.
[SimpleSVGBrowser.zip](https://github.com/javafxports/openjdk-jfx/files/3079721/SimpleSVGBrowser.zip)

The report by "Webbug" was:
STEPS TO FOLLOW TO REPRODUCE THE PROBLEM : 
1. Create an SVG file with a line and a polygon as follows: 

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" version="1.1" viewBox="0 0 500 500" xml:space="preserve" zoomAndPan="magnify"> 
  <polygon points="200,10 250,190 160,210" fill="green" onmouseover="this.style.fill='red'" onmouseout="this.style.fill='green'" onclick="if(this.style.fill=='red'){this.style.fill='green'}else{this.style.fill='red'}"/> 
  <line x1="100" y1="10" x2="250" y2="10" stroke="black" stroke-width="10" onmouseover="this.style.stroke='green'" onmouseout="this.style.stroke='black'" onclick="if(this.style.stroke=='black'){this.style.stroke='green'}else{this.style.stroke='black'}"/> 
</svg>`

2. Load the SVG file into the webEngine (webEngine.load("file:/mySVGFile.svg"); 
3. Move the mouse over the polygon. The polygon turns red. 
4. Move the mouse out of the polygon. The polygon turn back to green. 
5. Click on the polygon. the polygon turns red. 
6. Move the mouse over the line. 
7. move the mouse out of the line. 
8. click on the line. 

EXPECTED VERSUS ACTUAL BEHAVIOR : 

EXPECTED - 
1. When moving the mouse over the line, the line should turn green. 
2. When moving the mouse out of the line the line should turn black. 
3. When clicking on the line, the line should turn green and if clicked again turn black. 

ACTUAL - 
Nothing occurs. 
1. When moving the mouse over the line, the line stays black. 
2. When moving the mouse out of the line the line stays black. 
3. When clicking on the line, it stays black.

**Comment by kevinrushforth** [comment]
[JDK-8161284](https://bugs.openjdk.java.net/browse/JDK-8161284) is still an open bug, so no, it's not fixed.
