### ISSUE TITLE
build failure on travis, qt can't be downloaded

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#45]
Travis reports a build failure.

Looking in the logs shows this:
==> Downloading https://homebrew.bintray.com/bottles/qt-5.10.1.sierra.bottle.tar.gz
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "qt"
Download failed: https://homebrew.bintray.com/bottles/qt-5.10.1.sierra.bottle.tar.gz

I manually tried to download that file (qt) and it succeeded. Hence, I assume this was a temporal network problem and the build should continue to green with the next build. 
I keep this issue open until the build is green.

**Comment by ararunprasad** [comment]
Qt is no longer needed to build OpenJFX, Once it was required to build JFX along with WebKit.(i.e. -PCOMPILE_WEBKIT=true), but now OpenJFX WebKit uses cmake as a meta build system.

**Comment by brcolow** [comment]
@ararunprasad It would be nice if you could go through the list of deps declared in the `.travis.yml`: https://github.com/javafxports/openjdk-jfx/blob/develop/.travis.yml#L6 and let us know if any are now unnecessary. I added them following the "Building OpenJFX" wiki.

**Comment by ararunprasad** [comment]
@brcolow , Sure. I will raise a PR.

**Comment by johanvos** [comment]
fixed by #48
