### ISSUE TITLE
Does marlin render is  `Option Render` for javafx ? 

### ISSUE THREAD

**Issue by Jamlee** [javafxports/openjdk-jfx#452]
Does marlin render is  `Option Render` for javafx ? 

![image](https://user-images.githubusercontent.com/5196641/56577052-9c4d8200-65fc-11e9-87d6-687164797930.png)

**Comment by kevinrushforth** [comment]
I don't understand your question, but in any event, this issue tracker is not the place to ask general questions about JavaFX.

**Comment by Jamlee** [comment]
Could you recommand any good forum  to dicuss about general question ?

**Comment by nlisker** [comment]
@Jamlee FYI, Pisces will be removed in the future: https://bugs.openjdk.java.net/browse/JDK-8196079.

**Comment by kevinrushforth** [comment]
Also worth noting is that the choice of rasterizer should not generally matter to applications. It is an implementation detail.

@Jamlee To answer your question about forums, there is a (only somewhat active) developer forum here: https://community.oracle.com/community/groundbreakers/java/java_desktop/javafx_2.0_and_later

There is some documentation about getting started at http://openjfx.io/

Finally, there is a mailing list for the OpenJFX community, geared towards those who want to help contribute to OpenJFX development here: http://mail.openjdk.java.net/mailman/listinfo/openjfx-dev
