### ISSUE TITLE
OpenJFX 12.0.1 jmods download urls are not consistant with the release version number.

### ISSUE THREAD

**Issue by fthevenet** [javafxports/openjdk-jfx#453]
Starting with the release of OpenJFX 12.0.1, the download urls for pre-built jmods are not consistent with the release's version number, which breaks automated build for project using jlink to create modular image and need to first retrieve the jmods binaries.

This is the same issue as #279, which arose with release 11.0.1 and was subsequently fixed before reappearing with he release of 12.0.1

**Comment by johanvos** [comment]
URL's are changed, can you confirm it is fixed now?

**Comment by fthevenet** [comment]
Yes, I confirm it now works for both 12 and 12.0.1, using the same rules as for 11 -> 11.0.2
Thanks for the very prompt fix!
