### ISSUE TITLE
3DShapes with z-depth = 0  Black  in Pane 

### ISSUE THREAD

**Issue by phamvanthanh** [javafxports/openjdk-jfx#457]
Hi.
Color does not maintain when "Zoom" 3D shape in PANE.

I do not see this problem if zoom in Group.

This happens to Shapes and MeshView.

Please scroll mouse several times.

```
public class Shape3DBlack extends Application {
    double FACTOR = 1.1;
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        StackPane root = new StackPane();

        Box box = new Box();
        Pane boxG = new Pane(box);

        //DO NOT SEE FALSE BEHAVIORS IF "ZOOM" WITH GROUP
        //Group boxG = new Group(box);

        box.setWidth(100);
        box.setHeight(100);
        box.setDepth(0);

        PhongMaterial mat = new PhongMaterial();
        mat.setDiffuseColor(Color.RED);
        box.setMaterial(mat);

        root.getChildren().add(boxG);

        root.setOnScroll(event->{
            double deltaY = event.getDeltaY();
            if(deltaY > 0) {
                boxG.setScaleX(boxG.getScaleX() * FACTOR);
                boxG.setScaleY(boxG.getScaleY() * FACTOR);
                boxG.setScaleZ(boxG.getScaleZ() * FACTOR);

            }
            else {
                boxG.setScaleX(boxG.getScaleX() / FACTOR);
                boxG.setScaleY(boxG.getScaleY() / FACTOR);
                boxG.setScaleZ(boxG.getScaleZ() / FACTOR);

            }
        });

        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.show();


    }
}
```

**Comment by phamvanthanh** [comment]
More specific, this happens when setScaleZ.

**Comment by nlisker** [comment]
`Pane`s are not meant to hold 3D shapes, they are used for 2D layout. I'm going to assume that this is not a bug.

**Comment by kevinrushforth** [comment]
Even if it is a bug, it isn't using the API the way it is meant to be used. One other thing to look at: there are known issues with 3D rendering with a (default) `ParallelCamera`. Try a `PerspectiveCamera` instead.

**Comment by phamvanthanh** [comment]
Thank you for pointing out.
I want to have options of 2D views (XY, XZ...) with zoom (like autocad). Not one 3D shape but many shapes.

This question should not be here but could someone please advise a directive way of use?

**Comment by nlisker** [comment]
If you need help using JavaFX I suggest that you ask on StackOverflow. You can post a link to the question here.
