### ISSUE TITLE
FX12 Module jdk.unsupported.desktop not found

### ISSUE THREAD

**Issue by Jugen** [javafxports/openjdk-jfx#458]
I have a non modular FX application that successfully launches with FX **11** (and the full JRE **11**) using:

    jre\bin\java -p jfx/lib --add-modules ALL-MODULE-PATH -jar myapp.jar

However with FX **12** (and the full JRE **11**) I immediately get the following exception on startup:

    FindException: Module jdk.unsupported.desktop not found, required by javafx.swing

I'm certain that this is as a result of [JDK-8210092](https://bugs.openjdk.java.net/browse/JDK-8210092) and [JDK-8211249](https://bugs.openjdk.java.net/browse/JDK-8211249) mentioned in the release notes.

So is this a regression or am I supposed to modify the command line parameters ?

**Comment by kevinrushforth** [comment]
Your JRE 11 is missing a module that is now required for javafx.swing to run (it was optional at runtime in FX 11, although javafx.swing needs it to run propertly). See [JDK-8210092](https://bugs.openjdk.java.net/browse/JDK-8210092) and [JDK-8210759](https://bugs.openjdk.java.net/browse/JDK-8210759).

It looks like your JRE 11 is not complete. You need to include the `jdk.unsupported.desktop` module in order for the `javafx.swing` module to be resolved.

**Comment by Jugen** [comment]
Thanks @kevinrushforth,

Then both the Hotspot and OpenJ9 **JRE** 11.0.3_7 from OpenJDK are incomplete. (However it does work with the JDKs.)

**Comment by kevinrushforth** [comment]
> Then both the Hotspot and OpenJ9 JRE 11.0.3_7 from OpenJDK are incomplete.

Seems like it. I would take this up with the OpenJ9 folks.
