### ISSUE TITLE
Error when updating from JavaFX 11 to JavaFX 12

### ISSUE THREAD

**Issue by madoar** [javafxports/openjdk-jfx#461]
When updating the application [Phoenicis PlayOnLinux 5](https://github.com/PhoenicisOrg/phoenicis) from JavaFX 11 to JavaFX 12, an exception is thrown:

```
java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.monocle.MonocleTimer does not define or inherit an implementation of the resolved method abstract _pause(J)V of abstract class com.sun.glass.ui.Timer.
	at com.sun.glass.ui.Timer.pause(Timer.java:143)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pauseTimer(QuantumToolkit.java:501)
	at com.sun.javafx.tk.quantum.QuantumToolkit.postPulse(QuantumToolkit.java:488)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:344)
	at com.sun.glass.ui.monocle.MonocleTimer$1.run(MonocleTimer.java:58)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

We are unsure whether the reason is because of the project code (we're using JavaFX 11 without modules) or if the problem is located in JavaFX or TestFX.

For more details please see https://github.com/PhoenicisOrg/phoenicis/pull/1933 and the corresponding [travis logs](https://github.com/PhoenicisOrg/phoenicis/runs/109505118)

**Comment by johanvos** [comment]
Can you provide some information on how you get the javafx modules? In particular, where does MonocleTimer originates from (a jar from the SDK or from maven central?)
The source code for MonocleTimer does define the pause method, so I wonder where your classfile comes from.

Thanks!

**Comment by madoar** [comment]
Every dependency should originate from maven central, see also the corresponding [pom.xml](https://github.com/PhoenicisOrg/phoenicis/blob/master/phoenicis-javafx/pom.xml) of the master branch.

**Comment by kevinrushforth** [comment]
The Monocle classes are not included with the JavaFX modules, so I would suspect they come from TestFX.
@brcolow - can you comment?

**Comment by brcolow** [comment]
I think what happened here is that Monocle was broken by https://github.com/javafxports/openjdk-jfx/commit/828f80887a8d37a878808d317e7c66d9713b5ec8#diff-a7f54b20f741c7d485d445ec85aafc9c

As can be seen this commit introduces two new abstract methods to the `Timer` class, `_pause` and `_resume`. However, these additional abstract methods were not implemented in `MonocleTimer`:

https://github.com/javafxports/openjdk-jfx/blob/a42b5841674ab7cd2704e0ea5fbcc94934d91c83/modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleTimer.java

This is one of the reasons I think Monocle should be included by default with Java so bugs like this would be easier to catch - even though I know that would add more "support surface area" to the JavaFX public API.

**Comment by brcolow** [comment]
We need to release a new version of Monocle that includes the changes from:

 https://github.com/javafxports/openjdk-jfx/commit/828f80887a8d37a878808d317e7c66d9713b5ec8#diff-a7f54b20f741c7d485d445ec85aafc9c

**Comment by johanvos** [comment]
We include Monocle as part of the armv6hf release, which is available for 11.0.2 but not yet for 12.

**Comment by brcolow** [comment]
To follow up to my comment, this issue IMO can be closed as it really is a TestFX issue only as the Monocle version is conflicting with the JavaFX version. I will release a new Monocle version soon (using my super handy dandy [automatic update script](https://github.com/TestFX/Monocle/blob/master/sync.sh).

**Comment by kevinrushforth** [comment]
> If Monocle were included by default on Windows, we could stop packaging a separate Monocle dependency that must be kept up to date to avoid issues like this.

Yes, there would be some benefit for headless testing if these classes were included with the JavaFX runtime. Unclear as to whether this would be useful enough to justify the extra weight of these classes (not just from a size point of view but also from a bug fixing point of view), but might be worth having a discussion on it.

> To follow up to my comment, this issue IMO can be closed as it really is a TestFX issue only as the Monocle version is conflicting with the JavaFX version.

Agreed.

**Comment by madoar** [comment]
@brcolow can you inform us (either in this issue or in https://github.com/PhoenicisOrg/phoenicis/pull/1933) when a new monocle version with a fix to the issue has been released?

That would be really useful, thanks alot!

**Comment by brcolow** [comment]
TestFX Monocle version  `jdk-12.0.1+2` has been released :)

**Comment by plata** [comment]
Will it be available from Maven central?

**Comment by brcolow** [comment]
Indeed - I have synced to Maven Central on Friday, it should be there soon.

**Comment by brcolow** [comment]
In fact it is already there, just not showing up on main Maven central UI:

http://central.maven.org/maven2/org/testfx/openjfx-monocle/jdk-12.0.1+2/

But you should be able to fetch it from the repository when building.
