### ISSUE TITLE
TreeTableView updateItem problem

### ISSUE THREAD

**Issue by sanrol** [javafxports/openjdk-jfx#462]
Create a  CellFactory for my TreeTableColumn "localname" (FXML)
something going rong after expand / collapse / expand the same Folder,
updateItem don't be called for the last item.

Example with Log:

```java
localname.setCellFactory((TreeTableColumn<DRElement,String> param) -> new TreeTableCell<DRElement,String>()
{
    @Override
    protected final void updateItem(String value, boolean empty)
    {
        super.updateItem(value,empty);

        if(empty)
        {
            setGraphic(null);
            setText(null);
        }
        else
        {
            DRElement element = getTreeTableRow().getItem();
            setGraphic(DAXRemote.app.icons.getIcon(element.getIcon()));
            setText(element.getName());

            System.out.println("Update " + this.getIndex() +  ". row " + element.getName());
        }
    }
});
``` 
first setup [OK]

Update 0. row local
Update 1. row conf
Update 2. row libs
Update 3. row filestore
Update 4. row datastore
Update 5. row skins
Update 6. row service
Update 7. row SoloContacts.js
Update 8. row classloader.php
Update 9. row service.php

click expand folder skins (+1 Row SSDGreen.js) [OK]

Update 6. row SSDGreen.js
Update 7. row service
Update 8. row SoloContacts.js
Update 9. row classloader.php
Update 10. row service.php

click collapse folder skins (-1 Row SSDGreen.js) [OK]

Update 6. row service
Update 7. row SoloContacts.js
Update 8. row classloader.php
Update 9. row service.php

click expand folder skins (+1 Row SSDGreen.js) [FAIL]

Update 6. row SSDGreen.js
Update 7. row service
Update 8. row SoloContacts.js
Update 9. row classloader.php

**??? -> Update 10. row service.php -> updateItem is not call**
Result is:

![Bildschirmfoto 2019-05-04 um 12 30 46](https://user-images.githubusercontent.com/50264635/57178587-260a1480-6e73-11e9-9e0a-951bcab3d374.png)

JavaFX SDK 11.0.1 LTS
macOS Mojava 10.14.4
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

**Comment by sanrol** [comment]
do you need more information or is something missing?

**Comment by kevinrushforth** [comment]
> do you need more information or is something missing?

We will need a complete, standalone test program. Also, we will need a JBS bug to track it as indicated in the [Issue tracking](https://github.com/javafxports/openjdk-jfx#issue-tracking) section of the README.

However, unless this is a regression or a critical issue, it will go into our bug backlog with no particular time frame for getting it fixed. So if you are interested in contributing a fix, you can read [CONTRIBUTING.md](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md).
