### ISSUE TITLE
can't input chinese on CentOS7.6

### ISSUE THREAD

**Issue by opjkjava** [javafxports/openjdk-jfx#463]
On centOS7.6:
textfiled can't support chinese  input,  other application can do it. 
eg. firefox, terminal,gedit,wps-office, all are supporting.

evn:
openjdk 11.0.1
openjfx 11.0.1
GNOME Shell 3.28.3
fcitx.x86_64                         4.2.9.6-1.el7

**Comment by rooleongai** [comment]
I have met the same problom on my toplap with archlinux+kde,fcitx works well on the most application except wps when i input chinese
