### ISSUE TITLE
[JDK-8223760] static libs for macos

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#469]
See https://bugs.openjdk.java.net/browse/JDK-8223760: provide a mechanism to create static libs for macosx

**Comment by kevinrushforth** [comment]
I think this issue can be closed, too...

**Comment by johanvos** [comment]
> I think this issue can be closed, too...

true.

**Comment by johanvos** [comment]
Fixed via https://bugs.openjdk.java.net/browse/JDK-8223760
