### ISSUE TITLE
License terms for projects using openjfx

### ISSUE THREAD

**Issue by AlmasB** [javafxports/openjdk-jfx#487]
Suppose a library `X` has a dependency on openjfx. Given that openjfx is licensed under CC non-commercial, does that mean that projects that have a dependency / make use of the library `X` cannot produce commercial projects?

**Comment by kevinrushforth** [comment]
> Given that openjfx is licensed under CC non-commercial,

This is incorrect. OpenJFX is licensed under GPL v2 with the "Classpath" exception. See the [LICENSE](https://github.com/javafxports/openjdk-jfx/blob/master/LICENSE), [ADDITIONAL_LICENSE_INFO](https://github.com/javafxports/openjdk-jfx/blob/master/ADDITIONAL_LICENSE_INFO), and [ASSEMBLY_EXCEPTION](https://github.com/javafxports/openjdk-jfx/blob/master/ASSEMBLY_EXCEPTION) files.

This issue tracker is not the place to ask legal questions, so all I can do is refer you to the above files. If you need an interpretation of what the license terms mean or what they allow you to do, you will need to consult with an attorney.

**Comment by AlmasB** [comment]
Apologies. I seem to have confused OpenJFX and the website [openjfx.io](https://openjfx.io/), which in the footer states: `This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.` I guess "this work" refers to the website, rather than OpenJFX.

**Comment by kevinrushforth** [comment]
> I guess "this work" refers to the website, rather than OpenJFX.

Correct.
