### ISSUE TITLE
File Explorer nonfunctional in Mac OS

### ISSUE THREAD

**Issue by srikanthtumati** [javafxports/openjdk-jfx#495]
Attempting to create a file explorer in Mac OS 10.15 Catalina throws java[1272:61434] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted.

**Comment by kevinrushforth** [comment]
Without a test program, or at least a stack trace, we can't even tell whether this is a JavaFX problem or not, much less do anything about it.

**Comment by tanzim** [comment]
The reporter is likely doing this on macOS Catalina. This should cover it: https://bugs.openjdk.java.net/browse/JDK-8228457
