### ISSUE TITLE
Are there support to java 12?

### ISSUE THREAD

**Issue by Nizar4790k** [javafxports/openjdk-jfx#498]
Could not determine Java version using executable /home/Nizar4790k/Desktop/Apps/SDK/jdk-12.0.1/bin/java.

**Comment by kevinrushforth** [comment]
There is not enough information to even begin to know what your problem is. Further, this issue tracker is not the place to ask usage questions about Java or JavaFX. You might try StackOverflow or the openjfx-dev mailing list.
