### ISSUE TITLE
gitignore is missing entries

### ISSUE THREAD

**Issue by nlisker** [javafxports/openjdk-jfx#513]
The gitignore file is missing `bin/`. Without it, `.class` files are staged/indexed. There could be other entries that need to be ignored.

@kevinrushforth Can you check if other entries are missing?

**Comment by nlisker** [comment]
There's something else that I don't understand. Eclipse needs a different bin directory for compiled tests, which is called `testbin` (located on the same level as `bin`. Somehow hg ignores it, but git does not. I couldn't find what in hgignore would cause it to be ignored.

**Comment by kevinrushforth** [comment]
We can use https://bugs.openjdk.java.net/browse/JDK-8223722 to address any missing entries in `.gitignore`

**Comment by nlisker** [comment]
Added a comment in the JBS issue.
