### ISSUE TITLE
run JavaFX app using maven/gradle with Java 11

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#52]
This is an umbrella issue for tracking progress on the most important goal for now: making sure developers can easily create and run JavaFX applications when Java 11 is released. 

this involves:
* making sure we can build JavaFX using Java 11 (or any JDK that doesn't contain the JavaFX modules), tracked by https://bugs.openjdk.java.net/browse/JDK-8195798
* allow to build a JavaFX SDK: tracked by https://bugs.openjdk.java.net/browse/JDK-8198329
* allow to use maven/gradle and use the JavaFX modules in the following style:
```
dependencies {
    compile 'javafx:javafx.controls:11.0.0'
}
```

**Comment by mocobeta** [comment]
Thank you so much for your efforts to make this progress!
Sorry if here is not the right place for asking questions, but I have a question about licensing.

We are running an active OSS project atop of JavaFX which is distributed under Apache License.
https://github.com/DmitryKey/luke

We are happy to find this issue :), so my question is: 
If we add the dependency for OpenJFX module in our pom file, do we also need to change our license terms?
I know here is the "CLASSPATH exception" terms in the GPL license. But I am not an expert, not sure about it is legal that we keep ALv2 license while we link to OpenJFX module. 
https://github.com/javafxports/openjdk-jfx/blob/develop/LICENSE

I googled matters about dynamic linking to GPL projects, I still do not catch the point clearly.
I will be glad to hear your suggestions.

**Comment by mocobeta** [comment]
Apologize for the obscure question. We asked to ASF legal if it is allowed to add JavaFX/OpenJFX  dependency to Apache products.
Here is the discussion issue, if someone interested:
https://issues.apache.org/jira/browse/LEGAL-396?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16551865#comment-16551865

Thanks

**Comment by JonasWilms** [comment]
I think this can be closed?
https://mvnrepository.com/artifact/org.openjfx

**Comment by Xerus2000** [comment]
The repo is pretty useless on its own, adding it as a compile dependency does nothing. 
This is what you should be pointing to, at least for Gradle: https://github.com/openjfx/javafx-gradle-plugin

**Comment by Xerus2000** [comment]
I was talking about the maven repo

**Comment by kevinrushforth** [comment]
I see. If you are using it from gradle, then yes, the gradle plugin is very helpful. If using it directly from maven, the repo on maven central is probably sufficient.
