### ISSUE TITLE
SceneBuilder should highlight everything that differs from default

### ISSUE THREAD

**Issue by daveyostcom** [javafxports/openjdk-jfx#528]
It would be very useful if SceneBuilder would call attention to everything that differs from the default: individual settings in the Inspector, Inspector headings (Properties, Layout, Code), items in the hierarchy, struts in the Content Panel.

Having to scan around for settings of interest wastes time and adds cognitive load.

**Comment by kevinrushforth** [comment]
SceneBuilder has its own project: https://github.com/gluonhq/scenebuilder
