### ISSUE TITLE
Collapsable sections in the Inspector

### ISSUE THREAD

**Issue by daveyostcom** [javafxports/openjdk-jfx#529]
It is always better not to be constrained to seeing only one thing at a time.
1. The Inspector should be an accordion within an accordion.
2. The accordion layout should allow more than one section to be visible at a time; currently it allows expanding only one section, even if there is room for more.

**Comment by daveyostcom** [comment]
Each subsection, such as Layout > Size, should allow 3 states
• collapsed
• fully expanded
• showing only nondefault items

**Comment by kevinrushforth** [comment]
SceneBuilder has its own project: https://github.com/gluonhq/scenebuilder
