### ISSUE TITLE
PlatformImpl.startup stuck if exception thrown on first call

### ISSUE THREAD

**Issue by ahus1** [javafxports/openjdk-jfx#532]
Observation: When the first call to `PlatformImpl.startup()` fails with a runtime exception for example due to a missing library, the state of the class is in an undefined state; all further calls will hang. 

Expected behavior: 
* a second call to `PlatformImpl.startup()` should retry the initialization or should fail with an exception that this can't be retried
* all pending `runLater()` should terminate upon a failed initialization 

Analysis of the cause: 
1. on the first call to `PlatformImpl.startup()` will issue `initialized.getAndSet(true)` that sets the boolean variable to true
2. when the `Toolkit.getToolkit().startup()` fails, `startupLatch.countDown()` will never be called
3. a second call of `PlatformImpl.startup()` will check `initialized`, and enqueue for an initialization that will never happen

Environment where this happens: 
* Java 8 w/ JavaFX 8 - but the code-structure is unchanged in master; happend "in the wild" on on Ubuntu 19.04 after a "java.lang.UnsatisfiedLinkError: Can't load library: /home/john/idea/idea-IU-191.7479.19/jre64/lib/amd64/libglassgtk3.so" (https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/299)

**Comment by kevinrushforth** [comment]
It would take a fair bit of work to allow FX to be initialized more than once, and isn't likely to solve your problem anyway (which seems like a system / environment issue). I also note that calling into PlatformImpl::startup is not a supported mechanism to launch FX in JDK 8. If you can reproduce it with the latest (FX 13) release then we can take a look at it, although it isn't likely to be a high priority.

**Comment by ahus1** [comment]
@kevinrushforth - I see that the public API Platform::startup() will always pass preventDuplicateCalls, therefore this will not happen via that API. As the JDK 8 API doesn't allow me to check if PlatformImpl.startup() has been called before, I'll have to figure out a workaround. 

AFAIK there is no other way to launch FX inside of Swing without calling PlatformImpl::startup on JDK8?! Nevermind...

**Comment by kevinrushforth** [comment]
On FX 8, you can call `new JFXPanel()` (which also works on FX 9 and later).
