### ISSUE TITLE
Missing deployment manual

### ISSUE THREAD

**Issue by amkhlv** [javafxports/openjdk-jfx#536]
How to deploy a JavaFX app?

Even just on Ubuntu, forget Windows and OS/X. Asking the end user to download and unzip Gluon SDK is too complex, forget it. Even if I somehow convince a person to do it, I have to tell them to run, **in the terminal**, `java --module-path ~/.local/lib/javafx-sdk-11.0.2/lib/ --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphic ...` seriously?

What I need is a single `.jar` file, the user clicks on it and the thing fires up.

I really do not want to sound negative, I just want to understand ...
What is the philosophy behind JavaFX ? Is it supposed to be used on a desktop? 
The website https://openjfx.io/ mentions desktop use on the front page...
Who are the intended users? Is it only for corporations?

I googled for deployment manual, but could not find anything.

**Comment by nlisker** [comment]
> How to deploy a JavaFX app?

> What I need is a single .jar file, the user clicks on it and the thing fires up.

See "Runtime images" in https://openjfx.io/openjfx-docs/.

> Is it supposed to be used on a desktop?

Yes, and there's also a [JavaFXPorts](https://gluonhq.com/products/mobile/javafxports/) for mobile and embedded.

> Who are the intended users?

Anyone

**Comment by amkhlv** [comment]
Thank you !  Is there any way to achieve this with SBT assembly plugin ?

**Comment by eugener** [comment]
Since the SBT plugin does exists ( as far as I know), it is probably easier to convert the project to Gradle or Maven

**Comment by amkhlv** [comment]
The site says Java 12. Where can I find instructions for Java 11 ?

**Comment by eugener** [comment]
There should be no difference as far as using plugins. It comes down to setting correct version of JavaFX. Starting with JavaFX 11 all versions of it available from Maven Central

**Comment by amkhlv** [comment]
Yes, this works. Thank you for your kind explanations !
