### ISSUE TITLE
exporting com.sun.javafx.* packages would be useful to other libraries trying to integrate with OpenJFX

### ISSUE THREAD

**Issue by ntherrien** [javafxports/openjdk-jfx#538]
Hi!

I am using MVVMFX which is a great library that brings some MVVM concepts to JavaFX.  That library makes use of some of the com.sun.javafx* packages in order to provide a good level of integration with JavaFx.

Building code that uses MVVMFX on Java 11 results in errors like:
java.lang.IllegalAccessError: class javafx.scene.control.Control (in unnamed module @0x385f2bdc) cannot access class com.sun.javafx.application.PlatformImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x385f2bdc

Right now, the only way I know of to be able to keep using this library is to add appropriate --add-exports directives for each and every package used by MVVMFX. This ends up adding a *lot* of directives to the command line.

I wanted to know if the community would be open to the idea of having all JavaFX packages exported. Is there any particular reason why we would want to limit JavaFx integration with other libraries?

In my mind, JavaFx is just like the Java platform itself. I would expect all classes to be available so that we can leverage it and build on top of it. If we limit exports to *only* the packages an end-user would use, we essentially leave no room for others to build on top of it and expand.

I found another issue #511  where the user was asking for a similar thing. Again integration was at stake and from reading the comments it appears he decided to fork the project and remove the restrictions.

Looking forward to read your ideas on this,

- Nicolas

**Comment by kevinrushforth** [comment]
This is, quite simply, not something we would ever consider doing. All of the com.sun.* packages are internal implementation details and are not suitable for "opening up" as public API.

We are open to considering enhancements that add new public API, as was recently done for `VirtualFlow` and when we added a new public `Robot` class, but there are almost no cases where the right thing to do would be to "just open up" the existing implementation classes.
