### ISSUE TITLE
javafx file chooser hangs on macOS Catalina

### ISSUE THREAD

**Issue by jeffreyscurtis** [javafxports/openjdk-jfx#541]
Hello,

using javafx file chooser on macOS Catalina hangs with:
+[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted

I have reported this to apple, as it breaks with all versions of javafx including what included in netbeans 8.0  I. included a sample project which shows the issue

[HelloFX.zip](https://github.com/javafxports/openjdk-jfx/files/3438468/HelloFX.zip)

**Comment by kevinrushforth** [comment]
Already filed in JBS as: https://bugs.openjdk.java.net/browse/JDK-8228457

This bug also affects the AWT FileDialog: https://bugs.openjdk.java.net/browse/JDK-8227836

**Comment by jeffreyscurtis** [comment]
Ok thanks sorry didn’t see it

**Comment by kevinrushforth** [comment]
No worries. Thank you for reporting it, since we were unaware of it until someone in the community filed it just three days ago.

**Comment by kevinrushforth** [comment]
As an FYI, this bug is no longer reproducible with macOS 10.12 Catalina Beta7 (19A546d).

**Comment by darshanz** [comment]
Facing same problems on macOS Catalina 10.15 Beta (19A536g)

**Comment by kevinrushforth** [comment]
19A536g is Beta6, so is out of date. As mentioned above, Apple fixed the problem preventing FileChooser from running in Beta7 (19A546d).

**Comment by jeffreyscurtis** [comment]
I can confirm it’s fixed in latest beta, I also was asked by Apple to test on the latest beta and update my bug report which I did as resolved 
Thanks

**Comment by kevinrushforth** [comment]
Thanks for confirming.

**Comment by darshanz** [comment]
Thanks. Updated and confirmed.
