### ISSUE TITLE
How to modify component styles?

### ISSUE THREAD

**Issue by Krehizi** [javafxports/openjdk-jfx#564]
![捕获](https://user-images.githubusercontent.com/27603839/63079481-035ac200-bf71-11e9-88c8-1d2d7b143c19.PNG)
as shown in the figure,i wanted to modify the checkbox background and border through CSS, but it only worked on the external container, and the style of the checkbox did not change.
the javafx expose any methods to external modification?

**Comment by brcolow** [comment]
I recommend posting questions like this to a platform like StackOverflow. The Github issues is not the proper place.
