### ISSUE TITLE
Can an OpenJFX Branch be imported from the main repo?

### ISSUE THREAD

**Issue by CorneliaXaos** [javafxports/openjdk-jfx#572]
With how prevalent Java 8 applications are, there's bound to be a few JavaFX 8 applications one will come across.  I find myself wanting to build OpenJFX 8 from source, but would like to use this mirror.  Would it be possible to port over the last version of OpenJFX 8 from the main repo to this one so that it is accessible for persons like myself?

**Comment by kevinrushforth** [comment]
This `javafxports/openjdk-jfx repo` isn't the main repo, but rather a mirror of the main repo that is used as a sandbox to help reviews. In any case, no, this is not planned. OpenJFX 8u is no longer maintained, and is out of date and insecure. See [this message](https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-January/023039.html).

If someone wants to create a fork in another GitHub project they are welcome to do so under the terms of the license.
