### ISSUE TITLE
JDK-8230778: Build the javafx.web module with Python 3 instead of Python 2

### ISSUE THREAD

**Issue by ebourg** [javafxports/openjdk-jfx#579]
Python will be EOL on January 1st 2020 and the major Linux distributions are in the process of phasing it out. The javafx.web module relies on several Python 2 scripts to build and they don't work with Python 3. Converting them to Python 3 will be necessary to be able to build OpenFX on the upcoming Linux distributions.

**Comment by kevinrushforth** [comment]
I filed a pair of bugs in JBS to track this:

[JDK-8230779](https://bugs.openjdk.java.net/browse/JDK-8230779): WebKit build fails with python3
[JDK-8230778](https://bugs.openjdk.java.net/browse/JDK-8230779): Upgrade to python3 for building WebKit

If it is feasible, we should fix the build to allow WebKit to be built with either python2 or python3. This would be done ahead of actually switching the production builds to use python3.

**Comment by kevinrushforth** [comment]
@ebourg thanks for reporting this. We can use the two JBS issues to track this further.

**Comment by ebourg** [comment]
Thank you for forwarding the issue.

**Comment by shirishag75** [comment]
any update on this issue @kevinrushforth ?

**Comment by kevinrushforth** [comment]
This issue tracker is no longer being used. See the [above comment](#issuecomment-529676892) as to where it is being tracked.

**Comment by kevinrushforth** [comment]
To answer your question though, there has not yet been any progress on this.

**Comment by ebourg** [comment]
The OpenJDK issue tracker is closed to mere mortals unfortunately, I hope we'll still be able to use the GitHub one.
