### ISSUE TITLE
JavaFX Self-Contained Application fails with error "Failed to find library: jvm.dll"

### ISSUE THREAD

**Issue by pupeno** [javafxports/openjdk-jfx#59]
Some (about 25%) of the computers in which I install my app, packaged with javafxpackager, suffer this error, that has been reported already here: https://bugs.openjdk.java.net/browse/JDK-8191176

As far as I can see, all the information in that report is accurate so I won't copy it all again, except for the fact that it's still happening on version 8u172 b03.

Something that might be relevant is that I tried to workaround this issue by going to version 8u144 (before the bug happened) and I received this error when running `javafxpackager`:

```
Execution failed for task ':jfxNative'.
> Not found MSVC dlls
```

They do seem related as some people pointed out that the error loading jvm.dll is due to a missing `MSVCR100.dll`.

**Comment by kevinrushforth** [comment]
This issue should be filed in JBS by submitting a bug at: https://bugs.java.com/

This seems specific to JDK 8u. The openjdk-jfx sandbox repo on GitHub is for JavaFX 11 and beyond.
