### ISSUE TITLE
JavaFX and Netbeans web documention typos

### ISSUE THREAD

**Issue by odbuser2** [javafxports/openjdk-jfx#597]
The following page inconsistently refers to JDK13 and JavaFX13.

[https://openjfx.io/openjfx-docs/#IDE-NetBeans](https://openjfx.io/openjfx-docs/#IDE-NetBeans)

Change all references from JDK12 and JavaFX11/12 to JDK13 and JavaFX13.

**Comment by kevinrushforth** [comment]
Please file this issue here: https://github.com/openjfx/openjfx-docs
