### ISSUE TITLE
update README + CONTRIBUTING files

### ISSUE THREAD

**Issue by bourgesl** [javafxports/openjdk-jfx#6]
In master, those files are almost empty although it is THE first place newcomers will see.

**Comment by johanvos** [comment]
Yes, I have been thinking about that as well.
We have to be careful though as we're making changes to the mirror already (travis and appveyor) that are not going back upstream. 
But a README (that also includes CI status) makes perfect sense.
@kevinrushforth do you have an opinion on this?

**Comment by kevinrushforth** [comment]
I think as long as changes that are specific to the mirror (i.e., not going back upstream) are kept localized, ideally in separate files, that seems fine.

**Comment by johanvos** [comment]
Unless someone disagrees, I will move the CONTRIBUTING.md from https://github.com/johanvos/openjfxorg/blob/master/CONTRIBUTING.md (which I mentioned on the mailing list http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-February/021509.html) to the master, without first pushing it to develop and upstream to OpenJFX.

**Comment by bourgesl** [comment]
Only on github, I suppose ?

**Comment by johanvos** [comment]
yes

**Comment by eugener** [comment]
One small improvement we can do here is move all those mirror specific files into `.github` folder to keep things clean. This is one of the standard practices on GitHub. This folder can also contain issue templates, pull request templates and more.

**Comment by kevinrushforth** [comment]
I like the idea of a separate folder for mirror-specific files. In fact if you do this, it would make it easier / more palatable to merge these upstream in the near future, if desired.

**Comment by bourgesl** [comment]
Good idea.
Will github show the .github/readme on the project page ? that would be perfect

**Comment by eugener** [comment]
It does appear to be the case according to [GitHub Docs ](https://help.github.com/articles/about-readmes/)

**Comment by johanvos** [comment]
sounds good to me.
That means the README (we still have to write this) and the CONTRIBUTING.md only, or also other files?

**Comment by eugener** [comment]
New PR #18 covers the discussion around `.gihub` folder and related files. I also took a liberty to create an initial version of readme file, which includes build status badges from both TravisCI and AppVeyor. Check it out at my fork at https://github.com/eugener/openjdk-jfx

**Comment by johanvos** [comment]
PR #18 is merged
