### ISSUE TITLE
touch  event dosen't work

### ISSUE THREAD

**Issue by opjk** [javafxports/openjdk-jfx#602]
on x86 pad with ubuntu 16.04 OS,   javafx programe dosen't work.
click  the menu, buttom  in touch screen, no effectiveness
use mouse click them，is work。

openjdk  version:  11.0.2
openfx  version: 11.0.2, 13,

**Comment by goxr3plus** [comment]
We need to have a look at this .

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/) with a reproducible test case.
