### ISSUE TITLE
TreeTableView Regression: Indentation wrong using Label as column content type

### ISSUE THREAD

**Issue by DJViking** [javafxports/openjdk-jfx#607]
I think I have found a bug/regression with Java 11 regarding TreeTableView.
This has worked fine on JavaFX 8, but is messed up with JavaFX 11.
1) The arrow button is on the text
2) No text indentation levels: Each row (no matter the level) is at the left edge of the TreeTableView.

I have reproduced the same problem with JavaFX 12 and 13.

```java
TreeTableColumn<OurDataObject, Label> column = new TreeTableColumn<>("Column");
column.setCellValueFactory(param -> new ReadOnlyObjectWrapper<>(new OurDataObjectLabel(param.getValue().getValue())));
```

We are using Label here so we can set StyleClass based on some information in the OurDataObject.

Code Example for reproducing the problem:
I have also created a small project on GitHub for this example:
https://github.com/DJViking/test-app

```java
import javafx.application.Application;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeTableColumn;
import javafx.scene.control.TreeTableView;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        App.launch(args);
    }

    class OurDataObject {

        private final String name;

        public OurDataObject(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    class AlsoOurDataObject extends OurDataObject {

        private final String type;

        public AlsoOurDataObject(final String name,
                final String type) {
            super(name);
            this.type = type;
        }

        public String getType() {
            return type;
        }

    }

    class OurDataObjectLabel extends Label {

        public OurValueLabel(final OurDataObject data) {
            setText(data.getName());

            if (data instanceof AlsoOurDataObject) {
                AlsoOurDataObject alsoData = (AlsoOurDataObject) data;
                if (alsoData.getType() == "TYPE1") {
                    setStyle("-fx-font-weight: bold;");
                }
            }
        }

    }

    @Override
    public void start(Stage stage) throws Exception {
        StackPane root = new StackPane();

        TreeTableView<OurDataObject> treeTableView = new TreeTableView<>();
        treeTableView.setShowRoot(false);
        root.getChildren().add(treeTableView);

        TreeTableColumn<OurDataObject, Label> column = new TreeTableColumn<>("Column");
        column.setPrefWidth(200);
        treeTableView.getColumns().add(column);

        column.setCellValueFactory(param -> new ReadOnlyObjectWrapper<>(
                new OurDataObjectLabel(param.getValue().getValue())));

        TreeItem<OurDataObject> rootItem = new TreeItem<>(new OurDataObject(""));
        treeTableView.setRoot(rootItem);

        TreeItem<OurDataObject> item1 = new TreeItem<>(new OurDataObject("LEVEL1"));
        item1.setExpanded(true);
        rootItem.getChildren().add(item1);

        TreeItem<OurDataObject> item2 = new TreeItem<>(new OurDataObject("LEVEL2"));
        item2.setExpanded(true);
        item1.getChildren().add(item2);

        TreeItem<OurDataObject> item3 = new TreeItem<>(new AlsoOurDataObject("LEVEL2_1", "TYPE1"));
        item3.setExpanded(true);
        item2.getChildren().add(item3);

        Scene scene = new Scene(root, 250, 150);

        stage.setTitle("JavaFX and Gradle");
        stage.setScene(scene);
        stage.show();
    }

}
```

This is how it looks running JavaFX 11+
![Screenshot_20190930_120052](https://user-images.githubusercontent.com/3070076/65869214-4b477400-e37a-11e9-9f21-0ea3893d457a.png)

This is how it looks running JavaFX 8.
![Screenshot_20190930_120038](https://user-images.githubusercontent.com/3070076/65869221-4f739180-e37a-11e9-8425-0b545c28d06f.png)

**Comment by jasons2000** [comment]
I've had this problem, there's a simple workaround, which I can't remember off the top of my head. will dig out detail when I get  a chance, shortly.

**Comment by kevinrushforth** [comment]
Since you have a reproducible test case, can you file a bug at [bugreport.java.com](https://bugreport.java.com)?

**Comment by DJViking** [comment]
> We will review your report and have assigned it an internal review ID : 9062382.

**Comment by kevinrushforth** [comment]
https://bugs.openjdk.java.net/browse/JDK-8231644

**Comment by DJViking** [comment]
@jasons2000 I would like to hear about your workaround.
I know this repo is now closed, but I have no other means of contacting @jasons2000

**Comment by gergang** [comment]
Is there a workaround? I have the same problem and it looks like the jdk bug system is not taken seriously. I have this problem with all combinations of OpenJava JDK and Javafx 11 and 14.

**Comment by kleopatra** [comment]
don't use Nodes as data is the easiest way out ;)

**Comment by gergang** [comment]
Thanks for the hint (although I don't get it). But reading the thread again I think that I have a slightly different problem: Labels work fine. Indentation is only messed up for Buttons, RadioButtons and Checkboxes above JavaFX 8. I'll open a new thread, as this one is closed.
