### ISSUE TITLE
A small issue on Mac. Double click title bar can't restore to previous size

### ISSUE THREAD

**Issue by lvxingtu** [javafxports/openjdk-jfx#610]
When I click title bar twice quickly , a application should be enlarge, and double click title bar again, the window should restore to previous size. The problem is JavaFX application can't  resize to previous size when double click title bar. 

I try a simple application from official maven example which only a stage containing a label.
I also try three JavaFX versions since 11.0.2 , and all of them have this problem.
 
But the Ensemble8 app in App Store don't have this problem, I haven't install java 8 on my Mac, so I didn't test the issue with JavaFX8, Maybe it's not a problem with JavaFX8.

openjdk version: 12.0.2
openfx version: 11.0.2, 13, 14-ea+1
Mac version: macOS Mojave 10.14.6

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com).

If you are interested in contributing a fix for this issue, please see [CONTRIBUTING.md](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md) in the official [openjdk/jfx](https://github.com/openjdk/jfx) GutHub repo.
