### ISSUE TITLE
Sometimes the interface does not refresh

### ISSUE THREAD

**Issue by RichardWan1** [javafxports/openjdk-jfx#612]
![image](https://user-images.githubusercontent.com/24708672/66731763-88882780-ee8b-11e9-97c5-27aefd9765bd.png)

![image](https://user-images.githubusercontent.com/24708672/66730967-5b397a80-ee87-11e9-8374-418c92cfcd71.png)

If there is only one part, everything is fine, the stock market presentation by TableView is perfect.
But if we have more than two parts running at the same time, the stock market presentation maybe stop refresh for a few seconds. The more parts running, the greater probability of stopping refresh.

If nothing is done, it will automatically recover refresh after a few seconds, and if change to anther part or maximize the client, it will recover refresh immediately.

![image](https://user-images.githubusercontent.com/24708672/66730527-f2510300-ee84-11e9-9beb-134f9f315a8e.png)

How to solve the problem of stopping refresh?

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com).

If you are interested in contributing a fix for this issue, please see [CONTRIBUTING.md](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md) in the official [openjdk/jfx](https://github.com/openjdk/jfx) GutHub repo.
