### ISSUE TITLE
WebView bloks JVM from exit on OJFX 13.0.1 OJDK 13.0.1 Windows 7

### ISSUE THREAD

**Issue by appsofteng** [javafxports/openjdk-jfx#614]
With OJFX 12.0.2 when I close the stage, both the stage and the JVM process terminate.
With OJFX 13.0.1 when I close the stage, the stage closes but the JVM process keeps running.
When I don't create the WebView and close the stage, both the stage and JVM process terminate.

```java
public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {

        WebView wv = new WebView();
        BorderPane root = new BorderPane();
        root.setCenter(wv);
        Scene scene = new Scene(root, 600, 600);
        stage.setScene(scene);
        stage.show();
    }
}
```

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/).
