### ISSUE TITLE
event.getTransferMode() never sees MOVE on Mac, only COPY or LINK

### ISSUE THREAD

**Issue by daveyostcom** [javafxports/openjdk-jfx#615]
When I run this [drag and drop demo code](https://docs.oracle.com/javafx/2/drag_drop/jfxpub-drag_drop.htm) on Mac, the default transfer mode is `COPY`, which is debatable, but in that case I expect the `Cmd` key to select `MOVE` transfer mode (as it does in the Finder). The `Cmd` key does not select `MOVE` mode, nor does any other combination of modifier keys. Furthermore, the `Cmd` key selects `null` as the transfer mode.

There are several problems here:
1. When the default transfer mode is `COPY` there should be a modifier key that selects `MOVE`.
2. The default transfer mode should be `MOVE`. Think a drawing program or text editor.
3. There should be a way for the code to select either `MOVE` or `COPY` as the default transfer mode.
4. On macOS, `Option` + `Cmd` should choose `LINK`, but in fact, `Ctrl` selects `LINK`.

Fixing 2 would be a breaking change, so I suggest that 3 should be the recommended workaround, and relying on the default should be deprecated.

**Comment by kevinrushforth** [comment]
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/).

**Comment by kevinrushforth** [comment]
I note that this is tracked by: https://bugs.openjdk.java.net/browse/JDK-8237329
