### ISSUE TITLE
Font issues on Mac

### ISSUE THREAD

**Issue by dbschema-pro** [javafxports/openjdk-jfx#621]
Here is an issue with default font rendering on MacOs with OpenJfx13. The font is the system default. The letters are too close one to another. 

![image](https://user-images.githubusercontent.com/60284259/73247778-f0038200-41b1-11ea-9b9d-2b29b0ada679.png)

This can be tested by downloading the application from dbschema.com  - it has 15 days free trial

**Comment by kevinrushforth** [comment]
This GitHub repo is obsolete, and the issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/). See the [README](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/README.md) file for a pointer to the correct repo.

**Comment by kevinrushforth** [comment]
I note that this has already been filed. You can track it here: https://bugs.openjdk.java.net/browse/JDK-8236689

**Comment by dbschema-pro** [comment]
I add one more sample image which I think it is related to this case. 
Please let me know if is a different issue.

![image](https://user-images.githubusercontent.com/60284259/73970898-42654100-491e-11ea-9085-d3f5ce431abc.png)

**Comment by kevinrushforth** [comment]
It looks like the same issue. Can you confirm whether you are running on macOS 10.15 and whether or not you have a High-DPI Retina display?
