### ISSUE TITLE
Alt-Tab Issue

### ISSUE THREAD

**Issue by dbschema-pro** [javafxports/openjdk-jfx#622]
Pressing ALT does activate Mnemonic keys, so pressing the corresponding key for a button will press the button. This works fine.
But in Windows, pressing Alt + Tab will switch to a different application. Pressing again Alt-Tab will switch back to the JavaFx application - this works fine. Switching back will find the button in the Mnemonic active state, so pressing a letter will trigger the button.

The fix for this would be to clean mnemonic activation each time an application goes in background.

**Comment by kevinrushforth** [comment]
This GitHub repo is obsolete, and the issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/). See the [README](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/README.md) file for a pointer to the correct repo.
