### ISSUE TITLE
Raspberry Pi 4 VideoCore VI HW Support

### ISSUE THREAD

**Issue by rnayabed** [javafxports/openjdk-jfx#624]
Currently javafx doesn't support hardware acceleration on raspberry pi 4 because of a different gpu than previous raspberry pi models. Currently one can only use the software pipeline to render, but that makes the program undoubtedly slow and stuttery. Is there any plan to support pi 4 gpu in the future?

**Comment by hexvalid** [comment]
bump

**Comment by jgneff** [comment]
The JavaFX repository moved to [openjdk/jfx](https://github.com/openjdk/jfx) on October 1, 2019. This repository is [now obsolete](https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-October/023578.html).

**Comment by rnayabed** [comment]
@jgneff why didnt they archive this then? it really becomes confusing

**Comment by jgneff** [comment]
I imagine it will be archived eventually, but I for one am still updating issues that were opened in this old repository (#521) but implemented by a pull request in the new repository (openjdk/jfx#60). I couldn't do that if this repository was archived.

It's great to have the official repository on GitHub now (this one was just a mirror), but the downside is that you can't open issues on GitHub anymore. You have to report them through the [Oracle Web site](https://bugreport.java.com/bugreport/). I usually end up creating a new repository for the bug report, [like this one](https://github.com/jgneff/openjdk-freetype), just so I can edit it, upload images, and format the text. The interface to the Oracle Java Bug Database for outsiders is very limited.
