### ISSUE TITLE
I can't create .jar files

### ISSUE THREAD

**Issue by CharlesPMaxwell** [javafxports/openjdk-jfx#629]
### Error: Java FX Packager: Can not build artifact - fx: deploy is not available in this JDK
---
**I have been looking for a solution to create .jar files for 2 months. But I cannot find any good solutions!**
### I want to have it as it was in the past, like Java 8! :(

**Comment by JavaFX-Fan** [comment]
Same error

**Comment by scientificware** [comment]
@JavaFX-Fan

OpenJDK is a multiverse
see https://www.azul.com/ for JDK+JFX

@JavaFX-Fan + @CharlesPMaxwell

This reprository is Dead 🙁
see https://github.com/openjdk/jfx
