### ISSUE TITLE
JVM crash with openJFX 14.0.1

### ISSUE THREAD

**Issue by rjahn** [javafxports/openjdk-jfx#630]
OS: win 10 (64bit)

Simply created a swing application with JFXPanel and WebView.

Deployment: Classpath

Added all jar files (except ..swt.jar) to classpath and copied all dlls to the same directory in the classpath.

Showing a web page with WebView/WebEngine stops the application without any jvm dumps or logs...

If I try the same application with openJFX 11.0.2, no crash

tried with openJDK 12 (32, 64 bit), openJDK 14 (64 bit)

same problem with openJFX 15 EA

**Comment by rjahn** [comment]
same application works on Mac OS, openJDK 12, 14 and openJFX 14.01

**Comment by kevinrushforth** [comment]
This issue tracker is not active. If you believe you have found a bug, then you can file one at https://bugreport.java.com/
