### ISSUE TITLE
Unexecutable javafx jar

### ISSUE THREAD

**Issue by arkscz** [javafxports/openjdk-jfx#633]
Hello!
I wrote an application and then exported it as a runnable jar. I select the "include the packages" radio box in eclipse while doing so. Here's what I get when I `java -jar toast.jar`
 I am using openjdk-14 and javafx 14.

> Graphics Device initialization failed for :  es2, sw
> Error initializing QuantumRenderer: no suitable pipeline found
> java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
> 	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
> 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
> 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
> 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
> 	... 1 more
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
> Caused by: java.lang.RuntimeException: No toolkit found
> 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
> 	at java.base/java.lang.Thread.run(Thread.java:832)

Any help would be very appreciated. Thank you for your time!

**Comment by kevinrushforth** [comment]
This issue tracker is not active. I suggest you ask your question on a forum like StackOverflow.
