### ISSUE TITLE
Version incompatibility (libavcodec / libavformat v58)

### ISSUE THREAD

**Issue by tretonis** [javafxports/openjdk-jfx#635]
On Ubuntu 20.04 LTS
Has version installed (libavcodec / libavformat v58)

However there is a JavaFX program that requires v57
and presents this error:
error while loading shared libraries: libavcodec.so.57: cannot open shared object file: No such file or directory

What is the solution for this case?

Would it be more interesting for JavaFX to develop its own solution to run media and not rely on third party stuff?

**Comment by kevinrushforth** [comment]
This GitHub repo is obsolete, and the issue tracker is not actively tracked or managed. We will need a bug filed in the Java Bug System (JBS), which can be done at [bugreport.java.com](https://bugreport.java.com/). See the [README](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/README.md) file for a pointer to the correct repo.

Having said that, I checked and we added support for libav codec/format 58 in JavaFX 13. Are you using it from the downloaded maven modules? If so, I think I spotted a bug where we aren't explicitly loading the FX support library for v58. If you can confirm that is the case, I will file the bug for you. Also, if that is your problem, it should be possible to work around the bug.

**Comment by tretonis** [comment]
This error is being caused when you have a program with JavaFX 11 modules for example using V57 and the operating system has v58.

So this program doesn't run because of the media version.

example 
https://harmoniccode.blogspot.com/2020/03/cross-platform-gaming-spacefx.html#links

To see the error just have Linux  Ubuntu 20.04 with (libavcodec / libavformat v58) or any other with JavaFX 11.

**Comment by kevinrushforth** [comment]
Since you are using the JavaFX modules from `mavenCentral`, you will need to upgrade to JavaFX 13 or later in order to use libav 58 (and also to get any recent bug fixes). If you do that, and it still fails, then it might be because of the bug I alluded to above -- we aren't unpacking the `libavplugin-ffmpeg-58.so` library at initialization time, so it might not be found even though it is included in the `javafx.media-linux.jar` file. I'll file a bug for this latter problem.

**Comment by kevinrushforth** [comment]
I can confirm that this bug exists. I filed [JDK-8250238](https://bugs.openjdk.java.net/browse/JDK-8250238), and I plan to fix it in JavaFX 15.

**Comment by kevinrushforth** [comment]
As an FYI, the bug is now fixed and will be released in JavaFX 15.
