### ISSUE TITLE
ComboBox Prompt Not Displayed After Clearselection

### ISSUE THREAD

**Issue by pjacobsma** [javafxports/openjdk-jfx#636]
In any version of JavaFX above Java 1.8 the ComboBox prompt is not displayed after the clearSelection function is called on the ComboBox.  I have tested this with version 14 of JavaFX.  This does work correctly in the version of JavaFX bundled with Java 1.8.

**Comment by kleopatra** [comment]
please report a bug at the right place (not here, this rep is obsolete), details at https://bugreport.java.com/ and don't forget to include a small runnable example demonstrating the issue.

**Comment by kleopatra** [comment]
that said: can't reproduce it in a quick test .. might be something special in your context?
