### ISSUE TITLE
Created a jlink runtime and now my jar won't start up.

### ISSUE THREAD

**Issue by jonas-weimar** [javafxports/openjdk-jfx#638]
So basically I wrote an application using IntelliJ (on MacOS) and all worked fine. Then I build the artifacts and got my .jar version. To start this wherever I want to I decided to create a runtime using jlink, first getting my deps with jdeps:
![Bildschirmfoto 2020-09-14 um 12 01 53](https://user-images.githubusercontent.com/38507420/93072726-15ca9200-f682-11ea-8b42-591869557544.png)

After this I created the runtime using jlink:

![Bildschirmfoto 2020-09-14 um 12 02 53](https://user-images.githubusercontent.com/38507420/93072813-3a266e80-f682-11ea-81ba-d9663ee2e903.png)

This also worked fine for me. But then trying to run the jar I got this:

![Bildschirmfoto 2020-09-14 um 12 03 43](https://user-images.githubusercontent.com/38507420/93072877-575b3d00-f682-11ea-9c3d-24daa48611ca.png)

Used the flag to gather more information about it but idk what to do with it. Didn't find a solution yet that worked for me.

![Bildschirmfoto 2020-09-14 um 12 04 50](https://user-images.githubusercontent.com/38507420/93072987-7fe33700-f682-11ea-8e4b-b96b457e1519.png)

Help pleaaaase :((

**Comment by kevinrushforth** [comment]
This issue tracker is not active. I suggest you ask your questions like this on a forum like StackOverflow. Having said that, your problem is that you are trying to jlink to the sdk. You need to use the jmods instead.
