### ISSUE TITLE
Provide system tray support

### ISSUE THREAD

**Issue by Alex50505** [javafxports/openjdk-jfx#641]
As stated in an OpenJDK bug report [here](https://bugs.openjdk.java.net/browse/JDK-8092115), system tray support is a feature present in AWT but not in JavaFX. It is inconvenient to use AWT system tray with JavaFX, and it requires an extra AWT event queue thread, thus increasing the required system resources. I think we should add system tray support in JavaFX. Thanks!

**Comment by Alex50505** [comment]
Sorry, I accidentally closed this issue, so I reopened it.

**Comment by kleopatra** [comment]
don't - this is obsolete: the new location of the openjfx is https://github.com/openjdk/jfx

**Comment by Alex50505** [comment]
@kleopatra Oh, OK, thanks!

**Comment by Alex50505** [comment]
@kleopatra I can't find the issues section for the new GitHub repository.

**Comment by kevinrushforth** [comment]
You can file an issue in JBS as described in the README for https://github.com/openjdk/jfx

No need in this case, though, since it is already filed here: https://bugs.openjdk.java.net/browse/JDK-8092115

**Comment by Alex50505** [comment]
@kevinrushforth Yes, I already saw that it had been filed, but I also saw that it seemed like it had already gotten ignored, so I went here to file it. So right now, it seems like the only two "_solutions_" are to either use the AWT system tray or the SWT system tray.
