### ISSUE TITLE
Extending Shape or implementing DelegateShape

### ISSUE THREAD

**Issue by duncanmak** [javafxports/openjdk-jfx#642]
Hello,

I'm interested in having a Node in my scene graph that I can change later on, without losing its place in the scene.

I saw that in the old JavaFX 1.x, there used to be a type named [DelegateShape](https://docs.oracle.com/cd/E17802_01/javafx/javafx/1.3/docs/api/javafx.scene.shape/javafx.scene.shape.DelegateShape.html) which seems to be exactly what I'm looking for.

Is it possible to write my own DelegateShape in JavaFX 15?

I've tried defining my own Shape subclass, but the docs don't say what I need to override. There's also a line in the docs that says that:

> An application should not extend the Shape class directly. Doing so may lead to an UnsupportedOperationException being thrown.

**Comment by kevinrushforth** [comment]
As noted in the project README, this project an issue tracker is not active. The project repository is here: https://github.com/openjdk/jfx

This question is best asked on the [openjfx-dev](http://mail.openjdk.java.net/mailman/listinfo/openjfx-dev) mailing list, although this isn't likely a feature that we will support.
