### ISSUE TITLE
Wrong position of Japanese input on first edit of TextFieldTableCell

### ISSUE THREAD

**Issue by matintokyo** [javafxports/openjdk-jfx#644]
Normally the Japanese input character selection is shown right next to a TextField, but on the first edit of a TextFieldTableCell, it is shown at the top left of the screen. Please see attached image showing the issue.
After closing the field (via escape or enter) once and opening it again, the issue doesn't arise anymore.

I am creating the TextFieldTableCell using the code below:

`myColumn.setCellFactory(TextFieldTableCell.forTableColumn());`

I am using javafx  15.0.1 on Windows 10.

![InputPositionProblem](https://user-images.githubusercontent.com/38518687/104399638-67355000-5594-11eb-86c7-37e5ea2cb14a.jpg)

**Comment by kevinrushforth** [comment]
This GitHub repo is obsolete, and the issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/). See the [README](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/README.md) file for a pointer to the correct repo.
