### ISSUE TITLE
FX print tests fail with NPE in some environments

### ISSUE THREAD

**Issue by johanvos** [javafxports/openjdk-jfx#7]
See https://bugs.openjdk.java.net/browse/JDK-8196617

Since tests are failing on Windows, the AppVeyor CI complains about this.

**Comment by bourgesl** [comment]
I had a quick look at the code and actually many class fields (map, list) are only set if everything works fine (null protection is missing). It may be preferable to initialize such fields to empty collections and see if it is enough to let tests pass

**Comment by johanvos** [comment]
This is an area where I would like to see some general rules regarding null protection that can be followed everywhere in the code. My personal preference would also be initialising them with empty collections, but I know some people are against this and prefer lazy initialisation. 

Either way, the way it is done now doesn't sound right (there is only 1 method call (addPaper) that will initialise the Map  entities, but other methods might be called without the addPaper method ever be called, so it's obvious this will throw NullPointerExceptions).

**Comment by bourgesl** [comment]
I will have a look as I would like windows CI to be OK asap.
I propose to initialize collections and I will see if the build of the new PR becomes OK

**Comment by johanvos** [comment]
I agree (initialize collections).

**Comment by johanvos** [comment]
Does someone knows why the tests only fail on Windows and not on Linux/Mac?

**Comment by johanvos** [comment]
The reason why it works on Linux is that in 
`JobSettingsTest.setup(`) the following call returns null:
`job = PrinterJob.createPrinterJob()`;

On windows, there is a pseudoprinter, hence job is not null. The pseudoprinter is not initialized in the same way as a regular printer, hence the Maps are still null.

**Comment by bourgesl** [comment]
Good catch. I tried to fix NPE... but CI crashes with dump. Need some time to investigate

**Comment by johanvos** [comment]
The CI crash is due to the fact that tests on AppVeyor run with -PFULL_TEST=true. I suggest we create a separate issue for this, as it doesn't have to do with the failing printer tests (that are fixed with your patch).

**Comment by bourgesl** [comment]
See #24

**Comment by johanvos** [comment]
The PR in #24 solves this indeed. I think it would be good to create this as a separate PR though, and have the CI issue fixed in another PR?

**Comment by bourgesl** [comment]
See PR #32 submitted

**Comment by johanvos** [comment]
Fixed with PR #32
