### ISSUE TITLE
Bundle native parts in Jars

### ISSUE THREAD

**Issue by hendrikebbers** [javafxports/openjdk-jfx#76]
The first preview of a standalone JFX can be downloaded here: http://jdk.java.net/openjfx/
The release has a structure like this:
<img width="303" alt="jfx-structure" src="https://user-images.githubusercontent.com/9443847/39797278-93185200-535b-11e8-924a-5284153a394c.png">
While this is useable for me as a developer it will be really hard for clients that do not use a native application bundle. Other libraries (like [JNA](https://github.com/java-native-access/jna)) bundle the native libs (so, dll, ...) directly in the jar. By doing so JavaFX could be build as a jar with (os-specific) native parts. Once this is done you only need to add the FX-jar to your application and it could even be provided by jcenter and maven.
Based on Java modules it might make sense to not distribute one big Jar but one jar for each module.

**Comment by johanvos** [comment]
This is being discussed on the Panama mailing list (http://mail.openjdk.java.net/pipermail/panama-dev/2018-April/001541.html) and in jigsaw-dev

**Comment by hendrikebbers** [comment]
Well I think for the JRE / JDK it is a different topic since is always needed as a full package. but starting with Java 11 JavaFX will be external dependency.

**Comment by johanvos** [comment]
Then you are probably referring to what is discussed here: http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-April/021762.html

**Comment by johanvos** [comment]
It is being tackled in this PR: https://github.com/javafxports/openjdk-jfx/pull/83

**Comment by johanvos** [comment]
PR is merged
