### ISSUE TITLE
CI scripts should run "gradle all test"

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#85]
The CI scripts current just run the "gradle build" task, which builds the sdk and runs the test, but doesn't run the apps or javadoc tasks. Running "gradle all test" will catch additional errors without taking too much more time.

**Comment by kevinrushforth** [comment]
This could be done for either or both of the Travis or Appveyor builds.

**Comment by kevinrushforth** [comment]
The fix should be as simple as making the following change in the travis build script, and a similar change in the appveyor.yml script:

```
-sh ./gradlew build -PCONF=DebugNative -x :web:test --no-daemon --stacktrace --info
+sh ./gradlew all test -PCONF=DebugNative -x :web:test --no-daemon --stacktrace --info
```

**Comment by brcolow** [comment]
Fixed by https://github.com/javafxports/openjdk-jfx/pull/88
