### ISSUE TITLE
Use OpenJDK 10 for CI builds

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#86]
The CI builds currently use Oracle JDK 10 as the boot JDK for CI builds of FX. Now that we have switch to an unbundled JavaFX as the primary mode of building and distributing JavaFX bundles, the CI builds should switch to using OpenJDK 10 to match this. This will be a better test environment, as well as being needed eventually to produce actual build artifacts from CI builds.

**Comment by kevinrushforth** [comment]
@brcolow Can you take this issue?

**Comment by brcolow** [comment]
I can. I will get to it sometime today.

**Comment by brcolow** [comment]
Fixed by #88. Installing OpenJDK on macOS was non-trivial as there is no working homebrew package so it's a bit of a mess, but working. Installing OpenJDK on Linux was trivial (using bachus's install-jdk.sh script) and on Windows too because there is an OpenJDK chocolatey package.
