### ISSUE TITLE
Automatic merge from master into develop branch not run

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#90]
I merged pull request #88 into the master branch yesterday. I expected that this would get merged into develop soon after that, but it didn't (and still hasn't about 15 hours later).

@tiainen Is the sync job still running regularly? What triggers it?

**Comment by kevinrushforth** [comment]
I see that it was run just now. Was it kicked off manually, or on a timer?

**Comment by tiainen** [comment]
The job is run every hour around the 50 minute mark. It currently fails whenever changes are pushed to the master branch on github. The job executes the following script: https://github.com/javafxports/openjdk-jfx/blob/develop/.github/sync_upstream.sh

It fails at line 27 when trying to push to github, with the following message:

    Push master (github)
    To git@github.com:javafxports/openjdk-jfx.git
     ! [rejected]        master -> master (fetch first)
    error: failed to push some refs to 'git@github.com:javafxports/openjdk-jfx.git'
    hint: Updates were rejected because the remote contains work that you do
    hint: not have locally. This is usually caused by another repository pushing
    hint: to the same ref. You may want to first integrate the remote changes
    hint: (e.g., 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Currently, I fix this issue manually but as a permanent solution, I think we just need to pull in the changes from github/master before we do the push? This normally only fails when there are merge conflicts between the mercurial repository and the master branch on the github repository.

**Comment by kevinrushforth** [comment]
OK, thanks for the explanation. I think your proposed solution sounds fine. There shouldn't ever be merge conflicts as long as we follow the rule that commits pushed directly to master must only touch files that are not tracked in the upstream hg repo (e.g., .github/** or the Travis / appveyor CI files).

Until then, I'm happy to fix this manually on the rare occasions that I merge a PR into master.

**Comment by tiainen** [comment]
About fixing it manually, that's another issue. The job is currently run on a jenkins environment that is not publicly accessible. To fix it manually requires logging in to that machine and manually bring the local master branch up-to-date with the one on github.

For now I'll add a line in the script to perform a pull (fetch + merge) before pushing to github. That should get us a lot further already.
